// ─── Model-Specific AI Fingerprint Detection ─────────────────────────────────
// Detects stylistic fingerprints and patterns characteristic of specific AI
// code generators (ChatGPT/GPT-4, Claude, Copilot, Gemini, etc.).  These are
// not security vulnerabilities — they are signals that code was generated by a
// particular model and may carry that model's known biases or blind spots.
// ──────────────────────────────────────────────────────────────────────────────

import type { Finding } from "../types.js";
import { isCommentLine } from "./shared.js";

// ─── Fingerprint Pattern Registry ───────────────────────────────────────────

interface FingerprintSignal {
  /** Regex to detect the pattern */
  pattern: RegExp;
  /** Which model family this pattern is characteristic of */
  model: string;
  /** Human-readable description of the signal */
  description: string;
  /** Weight — how strongly this signal indicates the model (0–1) */
  weight: number;
  /** Whether to check comments (true) or code-only (false) */
  checkComments: boolean;
}

const FINGERPRINT_SIGNALS: FingerprintSignal[] = [
  // ── ChatGPT / GPT-4 signatures ──────────────────────────────────────────
  {
    pattern: /\/\/\s*(?:Example|Note|Remember|Important):\s/,
    model: "ChatGPT/GPT-4",
    description: 'Imperative tutorial-style comments ("Note:", "Remember:", "Important:")',
    weight: 0.3,
    checkComments: true,
  },
  {
    pattern: /\/\/\s*This\s+(?:function|method|class|variable|constant|module)\s+(?:is|will|does|handles|represents)/,
    model: "ChatGPT/GPT-4",
    description: 'Verbose "This function does X" documentation style in inline comments',
    weight: 0.3,
    checkComments: true,
  },
  {
    pattern: /\/\/ (?:Step \d|First,|Second,|Third,|Next,|Finally,|Then,)/,
    model: "ChatGPT/GPT-4",
    description: 'Sequential step-numbered comments ("Step 1:", "First,", "Then,")',
    weight: 0.4,
    checkComments: true,
  },
  {
    pattern: /console\.log\s*\(\s*['"`](?:Result|Output|Data|Response|Error|Success|Value|Hello):/,
    model: "ChatGPT/GPT-4",
    description: "Demonstration console.log with label-colon pattern",
    weight: 0.2,
    checkComments: true,
  },

  // ── Copilot signatures ───────────────────────────────────────────────────
  {
    pattern: /\/\/\s*TODO:\s*(?:implement|add|handle|fix|replace)\s/i,
    model: "Copilot",
    description: "Placeholder TODO stubs with generic verbs",
    weight: 0.2,
    checkComments: true,
  },
  {
    pattern: /(?:\/\/|#)\s*(?:Copilot|GitHub Copilot|Generated by Copilot)/i,
    model: "Copilot",
    description: "Explicit Copilot attribution comment",
    weight: 0.9,
    checkComments: true,
  },

  // ── Claude / Anthropic signatures ────────────────────────────────────────
  {
    pattern: /\/\/\s*(?:Let me|I'll|Here's|Here is|Let's)\s/,
    model: "Claude",
    description: 'Conversational first-person comments ("Let me", "I\'ll", "Here\'s")',
    weight: 0.4,
    checkComments: true,
  },
  {
    pattern: /\/\*\*\s*\n\s*\*\s*@(?:description|summary)\s+[A-Z][^.]+\.\s*\n\s*\*\s*\n\s*\*\s*@(?:param|returns)/,
    model: "Claude",
    description: "Dense multi-paragraph JSDoc with blank-line separators",
    weight: 0.3,
    checkComments: true,
  },

  // ── Gemini / Google signatures ───────────────────────────────────────────
  {
    pattern: /\/\/\s*(?:See|Refer to|For more information|Documentation):\s*https?:\/\//,
    model: "Gemini",
    description: "Inline URL documentation references",
    weight: 0.3,
    checkComments: true,
  },

  // ── Generic AI code signals (model-agnostic) ────────────────────────────
  {
    pattern: /(?:\/\/|#)\s*(?:Generated by|Auto-generated|AI[ -]generated|Created by AI|Written by AI)/i,
    model: "AI-generated",
    description: "Explicit AI-generation attribution comment",
    weight: 0.9,
    checkComments: true,
  },
  {
    pattern: /\/\/\s*[-─]{3,}\s*\w+.*[-─]{3,}/,
    model: "AI-generated",
    description: "Decorative section-divider comments with dashes",
    weight: 0.2,
    checkComments: true,
  },
];

// ─── Main Analyzer ──────────────────────────────────────────────────────────

export function analyzeModelFingerprint(code: string, _language: string): Finding[] {
  const findings: Finding[] = [];
  const lines = code.split("\n");
  const prefix = "MFPR";

  // Accumulate signals per model
  const modelSignals: Map<string, { lines: number[]; totalWeight: number; descriptions: string[] }> = new Map();

  for (const signal of FINGERPRINT_SIGNALS) {
    const matchedLines: number[] = [];

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const isComment = isCommentLine(line);

      // Only check comments for comment-only signals; check non-comments for code signals
      if (signal.checkComments && !isComment) continue;
      if (!signal.checkComments && isComment) continue;

      signal.pattern.lastIndex = 0;
      if (signal.pattern.test(line)) {
        matchedLines.push(i + 1);
      }
    }

    if (matchedLines.length > 0) {
      const existing = modelSignals.get(signal.model) ?? { lines: [], totalWeight: 0, descriptions: [] };
      existing.lines.push(...matchedLines);
      existing.totalWeight += signal.weight * Math.min(matchedLines.length, 3);
      if (!existing.descriptions.includes(signal.description)) {
        existing.descriptions.push(signal.description);
      }
      modelSignals.set(signal.model, existing);
    }
  }

  // Emit findings for models with sufficient signal accumulation
  let ruleNum = 1;
  for (const [model, data] of modelSignals) {
    // Require at least 2 distinct signal types OR one high-weight signal
    if (data.descriptions.length < 2 && data.totalWeight < 0.8) continue;

    const uniqueLines = [...new Set(data.lines)].sort((a, b) => a - b);
    const confidence = Math.min(0.9, 0.4 + data.totalWeight * 0.15);

    findings.push({
      ruleId: `${prefix}-${String(ruleNum++).padStart(3, "0")}`,
      severity: "info",
      title: `Code fingerprint matches ${model} generation patterns`,
      description:
        `Detected ${data.descriptions.length} stylistic signal(s) characteristic of ${model}-generated code: ` +
        data.descriptions.join("; ") +
        ". This is informational — AI-generated code should receive extra review for hallucinated APIs, " +
        "placeholder security comments, and model-specific blind spots.",
      lineNumbers: uniqueLines.slice(0, 10),
      recommendation:
        `This code shows patterns typical of ${model}. Review carefully for: ` +
        "(1) hallucinated imports/APIs, (2) placeholder security comments, " +
        "(3) incomplete error handling, (4) overly verbose or missing documentation. " +
        "Consider running the hallucination-detection and ai-code-safety judges specifically.",
      reference: "AI Code Safety — Model Fingerprint Detection",
      confidence,
      provenance: "regex-pattern-match",
    });
  }

  return findings;
}
