name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of @kevinrabun/judges are you using?
      placeholder: "1.2.0"
    validations:
      required: true

  - type: dropdown
    id: judge
    attributes:
      label: Affected Judge(s)
      description: Which judge(s) are involved?
      multiple: true
      options:
        - All / Tribunal
        - Accessibility
        - API Design
        - Cloud Readiness
        - Compliance
        - Concurrency
        - Cost Effectiveness
        - Cybersecurity
        - Data Security
        - Dependency Health
        - Documentation
        - Ethics & Bias
        - Internationalization
        - Observability
        - Performance
        - Reliability
        - Scalability
        - Software Practices
        - Testing

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Configure MCP server with...
        2. Run evaluate_code with...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Being Evaluated
      description: If applicable, paste the code that triggered the bug.
      render: typescript

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: MCP client, Node.js version, OS
      placeholder: |
        - MCP Client: Claude Desktop / VS Code Copilot / Cursor
        - Node.js: v22.x
        - OS: Windows 11 / macOS / Linux
    validations:
      required: true
