name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve the judges? We'd love to hear it.

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Judge
        - Existing Judge Improvement
        - Scoring / Verdict Logic
        - New Tool / Prompt
        - Documentation
        - CI / Infrastructure
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? What's missing today?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, links, or examples that help explain the request.
