/**
 * AI model trust — per-model confidence scoring based on
 * LLM source fingerprinting and finding patterns.
 *
 * All analysis is local — no telemetry or data upload.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";

// ─── Types ──────────────────────────────────────────────────────────────────

interface ModelProfile {
  id: string;
  name: string;
  patterns: string[];
  trustScore: number;
  strengths: string[];
  weaknesses: string[];
}

interface TrustRecord {
  model: string;
  file: string;
  trustScore: number;
  signals: string[];
  timestamp: string;
}

interface TrustStore {
  records: TrustRecord[];
  updatedAt: string;
}

const TRUST_DIR = ".judges-model-trust";
const TRUST_FILE = join(TRUST_DIR, "trust-history.json");

// ─── Model fingerprint database ─────────────────────────────────────────────

const MODEL_PROFILES: ModelProfile[] = [
  {
    id: "copilot",
    name: "GitHub Copilot",
    patterns: [
      "// Generated by Copilot",
      "// TODO: implement",
      "function handle",
      "const app = express()",
      "module.exports",
    ],
    trustScore: 72,
    strengths: ["Fast boilerplate", "Good Express/Node patterns", "IDE-integrated"],
    weaknesses: ["Weak input validation", "Often skips error handling", "May leak secrets in config"],
  },
  {
    id: "gpt-4o",
    name: "GPT-4o (ChatGPT)",
    patterns: [
      "// This function",
      "/**\n * @description",
      "try {\n  } catch (error)",
      "console.error(error)",
      "// Handle error gracefully",
    ],
    trustScore: 68,
    strengths: ["Verbose documentation", "Comprehensive try-catch", "Good API patterns"],
    weaknesses: ["Over-engineered abstractions", "Inconsistent naming", "Template strings in SQL"],
  },
  {
    id: "claude",
    name: "Claude (Anthropic)",
    patterns: ["// Note:", "// Important:", "// Safety check", "if (!input) throw", "// Validate input"],
    trustScore: 76,
    strengths: ["Input validation awareness", "Security-conscious", "Clear error messages"],
    weaknesses: ["Overly defensive code", "Verbose comments", "Complex type hierarchies"],
  },
  {
    id: "cursor",
    name: "Cursor AI",
    patterns: ["// @cursor", "// cursor:", "export default function", "useEffect(() =>", "'use client'"],
    trustScore: 70,
    strengths: ["React/Next.js patterns", "Modern TypeScript", "Component patterns"],
    weaknesses: ["Client-side secrets risk", "Missing CSP headers", "Weak API validation"],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    patterns: ["// Generated", "async function main()", "const result =", ".then(response =>", "// Process"],
    trustScore: 65,
    strengths: ["Clean async patterns", "Good Promise chains", "Concise code"],
    weaknesses: ["Missing error boundaries", "Weak auth patterns", "No rate limiting"],
  },
];

// ─── Core ───────────────────────────────────────────────────────────────────

function ensureDir(): void {
  if (!existsSync(TRUST_DIR)) mkdirSync(TRUST_DIR, { recursive: true });
}

function loadStore(): TrustStore {
  if (!existsSync(TRUST_FILE)) return { records: [], updatedAt: new Date().toISOString() };
  try {
    return JSON.parse(readFileSync(TRUST_FILE, "utf-8"));
  } catch {
    return { records: [], updatedAt: new Date().toISOString() };
  }
}

function saveStore(store: TrustStore): void {
  ensureDir();
  store.updatedAt = new Date().toISOString();
  writeFileSync(TRUST_FILE, JSON.stringify(store, null, 2));
}

function detectModel(content: string): { model: ModelProfile; confidence: number; signals: string[] } {
  let bestMatch = MODEL_PROFILES[0];
  let bestScore = 0;
  let bestSignals: string[] = [];

  for (const profile of MODEL_PROFILES) {
    const signals: string[] = [];
    let matchCount = 0;
    for (const pattern of profile.patterns) {
      if (content.includes(pattern)) {
        matchCount++;
        signals.push(pattern.slice(0, 40));
      }
    }
    const score = matchCount / profile.patterns.length;
    if (score > bestScore) {
      bestScore = score;
      bestMatch = profile;
      bestSignals = signals;
    }
  }

  return { model: bestMatch, confidence: Math.round(bestScore * 100), signals: bestSignals };
}

export function analyzeFileTrust(filePath: string): TrustRecord {
  const content = readFileSync(filePath, "utf-8");
  const { model, confidence, signals } = detectModel(content);

  // Adjust trust based on confidence
  const adjustedTrust = Math.round(model.trustScore * (0.5 + confidence / 200));

  const record: TrustRecord = {
    model: model.id,
    file: filePath,
    trustScore: adjustedTrust,
    signals,
    timestamp: new Date().toISOString(),
  };

  // Persist
  const store = loadStore();
  store.records.push(record);
  if (store.records.length > 500) store.records = store.records.slice(-500);
  saveStore(store);

  return record;
}

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runAiModelTrust(argv: string[]): void {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges ai-model-trust — AI model confidence scoring

Usage:
  judges ai-model-trust --file src/app.ts
  judges ai-model-trust --profiles
  judges ai-model-trust --compare copilot claude
  judges ai-model-trust --history

Options:
  --file <path>          Analyze a file for likely AI model source
  --profiles             Show all model profiles and trust scores
  --compare <a> <b>      Compare two model profiles side by side
  --history              Show trust analysis history
  --format json          JSON output
  --help, -h             Show this help
`);
    return;
  }

  const format = argv.find((_a: string, i: number) => argv[i - 1] === "--format") || "text";

  // Profiles
  if (argv.includes("--profiles")) {
    if (format === "json") {
      console.log(JSON.stringify(MODEL_PROFILES, null, 2));
    } else {
      console.log(`\n  AI Model Trust Profiles\n  ──────────────────────────`);
      for (const p of MODEL_PROFILES) {
        console.log(`    ${p.name.padEnd(22)} Trust: ${p.trustScore}/100`);
        console.log(`      Strengths:  ${p.strengths.join(", ")}`);
        console.log(`      Weaknesses: ${p.weaknesses.join(", ")}`);
        console.log("");
      }
    }
    return;
  }

  // Compare
  if (argv.includes("--compare")) {
    const idx = argv.indexOf("--compare");
    const a = argv[idx + 1];
    const b = argv[idx + 2];
    const profA = MODEL_PROFILES.find((p) => p.id === a);
    const profB = MODEL_PROFILES.find((p) => p.id === b);
    if (!profA || !profB) {
      console.error(`  Model not found. Available: ${MODEL_PROFILES.map((p) => p.id).join(", ")}`);
      return;
    }
    if (format === "json") {
      console.log(JSON.stringify({ a: profA, b: profB }, null, 2));
    } else {
      console.log(`\n  Model Comparison\n  ──────────────────────────`);
      console.log(`  ${"".padEnd(20)} ${profA.name.padEnd(25)} ${profB.name}`);
      console.log(`  ${"Trust Score".padEnd(20)} ${String(profA.trustScore).padEnd(25)} ${profB.trustScore}`);
      console.log(
        `  ${"Strengths".padEnd(20)} ${profA.strengths.length.toString().padEnd(25)} ${profB.strengths.length}`,
      );
      console.log(
        `  ${"Weaknesses".padEnd(20)} ${profA.weaknesses.length.toString().padEnd(25)} ${profB.weaknesses.length}`,
      );
      console.log("");
    }
    return;
  }

  // History
  if (argv.includes("--history")) {
    const store = loadStore();
    if (format === "json") {
      console.log(JSON.stringify(store, null, 2));
    } else {
      console.log(`\n  Trust Analysis History (${store.records.length} records)\n  ──────────────────────────`);
      for (const r of store.records.slice(-20)) {
        console.log(`    ${r.timestamp.slice(0, 10)}  ${r.model.padEnd(10)}  ${r.trustScore}/100  ${r.file}`);
      }
      console.log("");
    }
    return;
  }

  // Analyze file
  const filePath = argv.find((_a: string, i: number) => argv[i - 1] === "--file");
  if (!filePath) {
    console.error("  Use --file <path>, --profiles, or --history. --help for usage.");
    return;
  }

  if (!existsSync(filePath)) {
    console.error(`  File not found: ${filePath}`);
    return;
  }

  const result = analyzeFileTrust(filePath);
  const profile = MODEL_PROFILES.find((p) => p.id === result.model);

  if (format === "json") {
    console.log(JSON.stringify({ ...result, profile }, null, 2));
  } else {
    console.log(`\n  AI Model Trust Analysis — ${filePath}`);
    console.log(`  ──────────────────────────`);
    console.log(`  Likely model:  ${profile?.name || result.model}`);
    console.log(`  Trust score:   ${result.trustScore}/100`);
    console.log(`  Signals:       ${result.signals.length > 0 ? result.signals.join("; ") : "No strong signals"}`);
    if (profile) {
      console.log(`\n  Model strengths:  ${profile.strengths.join(", ")}`);
      console.log(`  Model weaknesses: ${profile.weaknesses.join(", ")}`);
    }
    console.log(`\n  Recommendation: ${result.trustScore >= 70 ? "Standard review" : "Enhanced review recommended"}`);
    console.log("");
  }
}
