/**
 * AI output compare — compare code generated by multiple AI models
 * from the same prompt to identify divergence, inconsistencies,
 * and model-specific patterns.
 *
 * All analysis local.
 */

import { existsSync, readFileSync } from "fs";

// ─── Types ──────────────────────────────────────────────────────────────────

interface FileAnalysis {
  file: string;
  lineCount: number;
  functionCount: number;
  importCount: number;
  commentRatio: number;
  complexity: number;
  patterns: string[];
}

interface ComparisonResult {
  files: FileAnalysis[];
  divergences: Divergence[];
  summary: {
    totalDivergences: number;
    highRisk: number;
    structuralSimilarity: number;
    recommendation: string;
  };
}

interface Divergence {
  type: string;
  severity: "high" | "medium" | "low";
  detail: string;
  files: string[];
}

// ─── Analysis ───────────────────────────────────────────────────────────────

function analyzeFile(filePath: string): FileAnalysis {
  const content = readFileSync(filePath, "utf-8");
  const lines = content.split("\n");

  const functionCount = (
    content.match(/\b(?:function\s+\w+|(?:const|let|var)\s+\w+\s*=\s*(?:async\s+)?(?:\([^)]*\)\s*=>|function))/g) || []
  ).length;
  const importCount = (content.match(/\b(?:import\s|require\s*\()/g) || []).length;
  const commentLines = lines.filter((l) => /^\s*(?:\/\/|\/?\*|#)/.test(l)).length;
  const commentRatio = lines.length > 0 ? Math.round((commentLines / lines.length) * 100) : 0;

  // Cyclomatic complexity estimate
  let complexity = 1;
  for (const line of lines) {
    if (/\b(?:if|else\s+if|switch|case|for|while|catch|&&|\|\||\?)\b/.test(line)) complexity++;
  }

  // Detect patterns
  const patterns: string[] = [];
  if (/\bclass\s+\w+/.test(content)) patterns.push("OOP");
  if (/=>\s*{|=>\s*\w/.test(content)) patterns.push("functional");
  if (/\basync\b/.test(content)) patterns.push("async");
  if (/\btry\s*{/.test(content)) patterns.push("error-handling");
  if (/\bdescribe\s*\(|\bit\s*\(|\btest\s*\(/.test(content)) patterns.push("test-code");
  if (/(?:express|fastify|koa|hapi)\b/.test(content)) patterns.push("web-framework");
  if (/\binterface\s|\btype\s/.test(content)) patterns.push("typed");

  return {
    file: filePath,
    lineCount: lines.length,
    functionCount,
    importCount,
    commentRatio,
    complexity,
    patterns,
  };
}

function findDivergences(analyses: FileAnalysis[]): Divergence[] {
  const divergences: Divergence[] = [];
  if (analyses.length < 2) return divergences;

  // Line count divergence
  const lineCounts = analyses.map((a) => a.lineCount);
  const maxLines = Math.max(...lineCounts);
  const minLines = Math.min(...lineCounts);
  if (maxLines > 0 && (maxLines - minLines) / maxLines > 0.3) {
    divergences.push({
      type: "size-divergence",
      severity: "medium",
      detail: `Line count varies significantly: ${minLines}–${maxLines} (${Math.round(((maxLines - minLines) / maxLines) * 100)}% spread)`,
      files: analyses.map((a) => a.file),
    });
  }

  // Complexity divergence
  const complexities = analyses.map((a) => a.complexity);
  const maxComp = Math.max(...complexities);
  const minComp = Math.min(...complexities);
  if (maxComp > minComp * 2) {
    divergences.push({
      type: "complexity-divergence",
      severity: "high",
      detail: `Cyclomatic complexity varies: ${minComp}–${maxComp} — models disagree on solution complexity`,
      files: analyses.map((a) => a.file),
    });
  }

  // Pattern divergence
  const allPatterns = new Set(analyses.flatMap((a) => a.patterns));
  for (const pattern of allPatterns) {
    const hasPattern = analyses.filter((a) => a.patterns.includes(pattern));
    const missingPattern = analyses.filter((a) => !a.patterns.includes(pattern));
    if (hasPattern.length > 0 && missingPattern.length > 0) {
      divergences.push({
        type: "pattern-divergence",
        severity: pattern === "error-handling" ? "high" : "low",
        detail: `Pattern "${pattern}" present in ${hasPattern.length}/${analyses.length} outputs`,
        files: missingPattern.map((a) => a.file),
      });
    }
  }

  // Import divergence
  const importCounts = analyses.map((a) => a.importCount);
  const maxImports = Math.max(...importCounts);
  const minImports = Math.min(...importCounts);
  if (maxImports > minImports + 3) {
    divergences.push({
      type: "dependency-divergence",
      severity: "medium",
      detail: `Import count varies: ${minImports}–${maxImports} — models chose different dependencies`,
      files: analyses.map((a) => a.file),
    });
  }

  // Comment ratio divergence
  const commentRatios = analyses.map((a) => a.commentRatio);
  const maxComment = Math.max(...commentRatios);
  const minComment = Math.min(...commentRatios);
  if (maxComment - minComment > 20) {
    divergences.push({
      type: "documentation-divergence",
      severity: "low",
      detail: `Comment ratio varies: ${minComment}%–${maxComment}% — inconsistent documentation level`,
      files: analyses.map((a) => a.file),
    });
  }

  // Function count divergence
  const fnCounts = analyses.map((a) => a.functionCount);
  const maxFn = Math.max(...fnCounts);
  const minFn = Math.min(...fnCounts);
  if (maxFn > 0 && maxFn > minFn * 2) {
    divergences.push({
      type: "decomposition-divergence",
      severity: "medium",
      detail: `Function count varies: ${minFn}–${maxFn} — models decompose differently`,
      files: analyses.map((a) => a.file),
    });
  }

  return divergences;
}

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runAiOutputCompare(argv: string[]): void {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges ai-output-compare — Compare outputs from multiple AI models

Usage:
  judges ai-output-compare <file1> <file2> [file3...]
  judges ai-output-compare copilot.ts claude.ts chatgpt.ts --format json

Options:
  --format json   JSON output
  --help, -h      Show this help

Compare code generated by different AI models for the same prompt.
Identifies divergences in complexity, patterns, structure, and dependencies.
High-divergence areas indicate model disagreement = higher risk.
`);
    return;
  }

  const format = argv.find((_a: string, i: number) => argv[i - 1] === "--format") || "text";
  const files = argv.filter((a: string) => !a.startsWith("--") && !argv[argv.indexOf(a) - 1]?.startsWith("--"));

  if (files.length < 2) {
    console.error("  Provide at least 2 files to compare (e.g., copilot.ts claude.ts)");
    return;
  }

  for (const f of files) {
    if (!existsSync(f)) {
      console.error(`  File not found: ${f}`);
      return;
    }
  }

  const analyses = files.map((f) => analyzeFile(f));
  const divergences = findDivergences(analyses);

  // Structural similarity score
  const totalChecks = 6;
  const divergentChecks = new Set(divergences.map((d) => d.type)).size;
  const similarity = Math.round(((totalChecks - divergentChecks) / totalChecks) * 100);

  const highRisk = divergences.filter((d) => d.severity === "high").length;
  let recommendation = "Outputs are highly consistent — any version is acceptable.";
  if (highRisk > 0) recommendation = "Significant divergences detected — manual review required before selecting.";
  else if (divergences.length > 2)
    recommendation = "Moderate divergences — prefer the version with best error handling and documentation.";

  const result: ComparisonResult = {
    files: analyses,
    divergences,
    summary: { totalDivergences: divergences.length, highRisk, structuralSimilarity: similarity, recommendation },
  };

  if (format === "json") {
    console.log(JSON.stringify(result, null, 2));
  } else {
    console.log(`\n  AI Output Comparison — ${files.length} files`);
    console.log(`  Structural Similarity: ${similarity}%\n  ──────────────────────────`);

    console.log(
      `\n    ${"File".padEnd(30)} ${"Lines".padEnd(8)} ${"Funcs".padEnd(8)} ${"Complex".padEnd(8)} ${"Comments".padEnd(10)} Patterns`,
    );
    console.log(`    ${"─".repeat(80)}`);
    for (const a of analyses) {
      console.log(
        `    ${a.file.substring(0, 28).padEnd(30)} ${String(a.lineCount).padEnd(8)} ${String(a.functionCount).padEnd(8)} ${String(a.complexity).padEnd(8)} ${(a.commentRatio + "%").padEnd(10)} ${a.patterns.join(", ")}`,
      );
    }

    if (divergences.length > 0) {
      console.log(`\n    Divergences (${divergences.length})`);
      for (const d of divergences) {
        const icon = d.severity === "high" ? "🔴" : d.severity === "medium" ? "🟡" : "🟢";
        console.log(`      ${icon} [${d.severity.toUpperCase()}] ${d.type}`);
        console.log(`         ${d.detail}`);
      }
    } else {
      console.log(`\n    ✅ No significant divergences detected`);
    }

    console.log(`\n    Recommendation: ${recommendation}\n`);
  }
}
