/**
 * Code owner suggest — auto-recommend CODEOWNERS entries
 * based on finding patterns and resolution history.
 *
 * All analysis uses local data only.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";

// ─── Types ──────────────────────────────────────────────────────────────────

interface OwnerSuggestion {
  path: string;
  suggestedOwner: string;
  reason: string;
  confidence: number;
  ruleCategories: string[];
}

interface OwnerStore {
  suggestions: OwnerSuggestion[];
  updatedAt: string;
}

const OWNER_DIR = ".judges-code-owners";
const OWNER_FILE = join(OWNER_DIR, "suggestions.json");

// ─── Core ───────────────────────────────────────────────────────────────────

function ensureDir(): void {
  if (!existsSync(OWNER_DIR)) mkdirSync(OWNER_DIR, { recursive: true });
}

function loadStore(): OwnerStore {
  if (!existsSync(OWNER_FILE)) return { suggestions: [], updatedAt: new Date().toISOString() };
  try {
    return JSON.parse(readFileSync(OWNER_FILE, "utf-8"));
  } catch {
    return { suggestions: [], updatedAt: new Date().toISOString() };
  }
}

function saveStore(store: OwnerStore): void {
  ensureDir();
  store.updatedAt = new Date().toISOString();
  writeFileSync(OWNER_FILE, JSON.stringify(store, null, 2));
}

function loadScoreData(): Array<{ author: string; findingsFixed: number; categories: string[] }> {
  // Try to load from dev-score data
  const scoreDir = ".judges-scores";
  if (!existsSync(scoreDir)) return [];
  try {
    const { readdirSync: rds } = require("fs");
    const files: string[] = rds(scoreDir).filter((f: string) => f.endsWith(".json"));
    return files.map((f: string) => {
      try {
        const data = JSON.parse(readFileSync(join(scoreDir, f), "utf-8"));
        return {
          author: data.author || f.replace(".json", ""),
          findingsFixed: data.findingsFixed || data.score || 0,
          categories: data.topCategories || [],
        };
      } catch {
        return { author: f.replace(".json", ""), findingsFixed: 0, categories: [] };
      }
    });
  } catch {
    return [];
  }
}

export function suggestOwner(path: string, author: string, ruleCategories: string[]): OwnerSuggestion {
  const suggestion: OwnerSuggestion = {
    path,
    suggestedOwner: author,
    reason: `Most active reviewer for ${ruleCategories.join(", ")} findings`,
    confidence: Math.min(100, 50 + ruleCategories.length * 10),
    ruleCategories,
  };

  const store = loadStore();
  // Replace existing suggestion for same path
  const idx = store.suggestions.findIndex((s) => s.path === path);
  if (idx >= 0) store.suggestions[idx] = suggestion;
  else store.suggestions.push(suggestion);
  if (store.suggestions.length > 200) store.suggestions = store.suggestions.slice(-200);
  saveStore(store);

  return suggestion;
}

function generateCodeowners(suggestions: OwnerSuggestion[]): string {
  const lines = [
    "# CODEOWNERS — Generated by judges code-owner-suggest",
    "# Review and customize before committing",
    "",
  ];
  const grouped = new Map<string, string[]>();
  for (const s of suggestions) {
    const existing = grouped.get(s.suggestedOwner) || [];
    existing.push(s.path);
    grouped.set(s.suggestedOwner, existing);
  }
  for (const [owner, paths] of grouped) {
    for (const p of paths) {
      lines.push(`${p} @${owner}`);
    }
  }
  return lines.join("\n") + "\n";
}

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runCodeOwnerSuggest(argv: string[]): void {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges code-owner-suggest — Auto-recommend CODEOWNERS entries

Usage:
  judges code-owner-suggest --analyze
  judges code-owner-suggest --suggest --path "src/auth/" --owner "alice@co.com" --rules SEC,AUTH
  judges code-owner-suggest --export
  judges code-owner-suggest --export --out CODEOWNERS

Options:
  --analyze               Auto-suggest from dev-score and finding data
  --suggest               Manually add a suggestion
  --path <path>           File/directory path for suggestion
  --owner <name>          Owner email/username
  --rules <csv>           Rule categories (comma-separated)
  --export                Export as CODEOWNERS format
  --out <file>            Write CODEOWNERS to file
  --format json           JSON output
  --help, -h              Show this help
`);
    return;
  }

  const format = argv.find((_a: string, i: number) => argv[i - 1] === "--format") || "text";

  // Manual suggestion
  if (argv.includes("--suggest")) {
    const path = argv.find((_a: string, i: number) => argv[i - 1] === "--path");
    const owner = argv.find((_a: string, i: number) => argv[i - 1] === "--owner");
    const rulesStr = argv.find((_a: string, i: number) => argv[i - 1] === "--rules");
    if (!path || !owner) {
      console.error("  --path and --owner required for --suggest");
      return;
    }
    const rules = rulesStr ? rulesStr.split(",") : [];
    const suggestion = suggestOwner(path, owner, rules);
    if (format === "json") {
      console.log(JSON.stringify(suggestion, null, 2));
    } else {
      console.log(`\n  ✅ Suggestion recorded:`);
      console.log(`     ${suggestion.path} → @${suggestion.suggestedOwner} (${suggestion.confidence}% confidence)`);
      console.log(`     Reason: ${suggestion.reason}\n`);
    }
    return;
  }

  // Auto-analyze
  if (argv.includes("--analyze")) {
    const devs = loadScoreData();
    if (devs.length === 0) {
      console.log("  No dev-score data found. Record developer activity with `judges dev-score` first.");
      return;
    }

    const suggestions: OwnerSuggestion[] = [];
    // Map categories to path prefixes
    const categoryPaths: Record<string, string> = {
      SEC: "src/security/",
      AUTH: "src/auth/",
      SQL: "src/database/",
      XSS: "src/frontend/",
      CRYPTO: "src/crypto/",
      SSRF: "src/network/",
      CMD: "src/commands/",
    };

    for (const dev of devs) {
      for (const cat of dev.categories) {
        const path = categoryPaths[cat] || `src/${cat.toLowerCase()}/`;
        suggestions.push(suggestOwner(path, dev.author, [cat]));
      }
    }

    if (format === "json") {
      console.log(JSON.stringify(suggestions, null, 2));
    } else {
      console.log(`\n  Auto-Analyzed Code Owners (${suggestions.length} suggestions)\n  ──────────────────────────`);
      for (const s of suggestions) {
        console.log(`    ${s.path.padEnd(25)} → @${s.suggestedOwner.padEnd(20)} ${s.ruleCategories.join(",")}`);
      }
      console.log(`\n  Export with: judges code-owner-suggest --export\n`);
    }
    return;
  }

  // Export
  if (argv.includes("--export")) {
    const store = loadStore();
    if (store.suggestions.length === 0) {
      console.log("  No suggestions yet. Use --analyze or --suggest first.");
      return;
    }

    const content = generateCodeowners(store.suggestions);
    const outPath = argv.find((_a: string, i: number) => argv[i - 1] === "--out");
    if (outPath) {
      writeFileSync(outPath, content);
      console.log(`  ✅ Written to ${outPath} (${store.suggestions.length} entries)`);
    } else {
      console.log(content);
    }
    return;
  }

  // Default: show current suggestions
  const store = loadStore();
  if (format === "json") {
    console.log(JSON.stringify(store, null, 2));
  } else {
    console.log(`\n  Code Owner Suggestions (${store.suggestions.length})\n  ──────────────────────────`);
    if (store.suggestions.length === 0) {
      console.log("    No suggestions yet. Use --analyze or --suggest to add.");
    } else {
      for (const s of store.suggestions) {
        console.log(
          `    ${s.path.padEnd(25)} → @${s.suggestedOwner.padEnd(20)} ${s.confidence}% ${s.ruleCategories.join(",")}`,
        );
      }
    }
    console.log("");
  }
}
