/**
 * Documentation generation — generates security documentation
 * from Judges findings history and configuration.
 *
 * All output is local markdown files.
 */

import { existsSync, readFileSync, mkdirSync, writeFileSync } from "fs";
import { join } from "path";

// ─── Types ──────────────────────────────────────────────────────────────────

interface DocSection {
  title: string;
  content: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function loadJsonSafe<T>(path: string, fallback: T): T {
  if (!existsSync(path)) return fallback;
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return fallback;
  }
}

function generatePolicyDoc(): DocSection[] {
  const sections: DocSection[] = [];

  // Header
  sections.push({
    title: "Security Review Policy",
    content: `# Security Review Policy\n\n_Generated by Judges on ${new Date().toISOString().split("T")[0]}_\n\n## Overview\n\nThis document outlines the security review policy enforced by the Judges automated code review system.\n`,
  });

  // Configuration
  const configPath = ".judgesrc";
  if (existsSync(configPath)) {
    try {
      const config = JSON.parse(readFileSync(configPath, "utf-8"));
      let content = `## Configuration\n\n`;
      if (config.preset) content += `- **Preset:** ${config.preset}\n`;
      if (config.minSeverity) content += `- **Minimum Severity:** ${config.minSeverity}\n`;
      if (config.disabledJudges?.length) content += `- **Disabled Judges:** ${config.disabledJudges.join(", ")}\n`;
      if (config.disabledRules?.length) content += `- **Disabled Rules:** ${config.disabledRules.join(", ")}\n`;
      content += `\n`;
      sections.push({ title: "Configuration", content });
    } catch {
      // skip
    }
  }

  // Suppressions
  const supps = loadJsonSafe<{ suppressions?: unknown[] }>(".judges-suppressions.json", { suppressions: [] });
  if (supps.suppressions && supps.suppressions.length > 0) {
    let content = `## Approved Suppressions\n\n| Rule | Reason | Approved By |\n|------|--------|-------------|\n`;
    for (const s of supps.suppressions as Array<{ ruleId?: string; reason?: string; approvedBy?: string }>) {
      content += `| ${s.ruleId || "—"} | ${s.reason || "—"} | ${s.approvedBy || "—"} |\n`;
    }
    content += `\n`;
    sections.push({ title: "Suppressions", content });
  }

  // Quality gates
  const gate = loadJsonSafe<Record<string, unknown>>(join(".judges-quality-gate", "policy.json"), {});
  if (Object.keys(gate).length > 0) {
    let content = `## Quality Gate Policy\n\n`;
    for (const [key, val] of Object.entries(gate)) {
      content += `- **${key}:** ${JSON.stringify(val)}\n`;
    }
    content += `\n`;
    sections.push({ title: "Quality Gate", content });
  }

  return sections;
}

function generateRemediationGuide(): DocSection[] {
  const sections: DocSection[] = [];

  sections.push({
    title: "Remediation Guide",
    content: `# Security Remediation Guide\n\n_Generated by Judges on ${new Date().toISOString().split("T")[0]}_\n\nThis guide covers common security findings and how to fix them.\n\n`,
  });

  const guides = [
    {
      rule: "SQL Injection",
      fix: "Use parameterized queries or prepared statements. Never concatenate user input into SQL strings.",
      example: "db.query('SELECT * FROM users WHERE id = ?', [userId])",
    },
    {
      rule: "Cross-Site Scripting (XSS)",
      fix: "Sanitize and encode all user-provided output. Use framework-provided escaping (e.g., React auto-escapes).",
      example: "const safe = DOMPurify.sanitize(userInput)",
    },
    {
      rule: "Command Injection",
      fix: "Use parameterized APIs or allowlists instead of shell execution with user input.",
      example: "execFile('git', ['log', '--oneline'], callback)",
    },
    {
      rule: "Hardcoded Secrets",
      fix: "Move secrets to environment variables or a secrets manager. Never commit credentials.",
      example: "const apiKey = process.env.API_KEY",
    },
    {
      rule: "Insecure Cryptography",
      fix: "Use strong algorithms (AES-256-GCM, SHA-256+). Avoid MD5, SHA-1, DES, RC4.",
      example: "crypto.createCipheriv('aes-256-gcm', key, iv)",
    },
    {
      rule: "Path Traversal",
      fix: "Validate and normalize file paths. Use allowlists for permitted directories.",
      example: "const safePath = path.resolve(baseDir, path.basename(userInput))",
    },
    {
      rule: "SSRF",
      fix: "Validate and allowlist URLs. Block internal IP ranges. Use URL parsing.",
      example: "const url = new URL(userInput); if (!ALLOWED_HOSTS.has(url.hostname)) throw new Error()",
    },
    {
      rule: "Missing Authentication",
      fix: "Require authentication on all sensitive endpoints. Use middleware for consistent enforcement.",
      example: "app.use('/api', authMiddleware)",
    },
  ];

  let content = "";
  for (const g of guides) {
    content += `## ${g.rule}\n\n**Fix:** ${g.fix}\n\n\`\`\`\n${g.example}\n\`\`\`\n\n---\n\n`;
  }

  sections.push({ title: "Remediation Details", content });
  return sections;
}

function generateTeamPlaybook(): DocSection[] {
  const sections: DocSection[] = [];

  sections.push({
    title: "Team Security Playbook",
    content: `# Team Security Playbook\n\n_Generated by Judges on ${new Date().toISOString().split("T")[0]}_\n\n## Workflow\n\n1. **Pre-commit**: Run \`judges review\` locally before pushing code\n2. **CI Pipeline**: Configure \`judges ci-template\` for automated PR checks\n3. **Triage**: Use \`judges auto-triage\` to prioritize critical findings\n4. **Review**: Assign findings using \`judges assign-findings\`\n5. **Track**: Monitor progress with \`judges burndown\`\n6. **Report**: Generate digests with \`judges digest\`\n\n`,
  });

  sections.push({
    title: "Escalation Procedures",
    content: `## Escalation Procedures\n\n| Severity | SLA | Action |\n|----------|-----|--------|\n| Critical | 4 hours | Notify security lead, create incident ticket |\n| High | 24 hours | Assign to code owner, block PR merge |\n| Medium | 1 week | Assign to team backlog |\n| Low | 1 sprint | Track in burndown |\n\n`,
  });

  sections.push({
    title: "Metrics",
    content: `## Key Metrics\n\n- **Mean Time to Remediate (MTTR)**: Track via \`judges sla-track\`\n- **False Positive Rate**: Tune via \`judges noise-advisor\`\n- **Coverage**: Monitor via \`judges coverage-map\`\n- **Team Score**: View via \`judges team-leaderboard\`\n- **Security Maturity**: Assess via \`judges security-maturity\`\n\n`,
  });

  return sections;
}

// ─── CLI ────────────────────────────────────────────────────────────────────

const STORE = ".judges-docs";

export function runDocGen(argv: string[]): void {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges doc-gen — Generate security documentation

Usage:
  judges doc-gen --policy
  judges doc-gen --remediation
  judges doc-gen --playbook
  judges doc-gen --all

Options:
  --policy              Generate security review policy document
  --remediation         Generate remediation guide
  --playbook            Generate team security playbook
  --all                 Generate all documents
  --output <dir>        Output directory (default: .judges-docs)
  --format json         JSON output
  --help, -h            Show this help
`);
    return;
  }

  const format = argv.find((_a: string, i: number) => argv[i - 1] === "--format") || "text";
  const outputDir = argv.find((_a: string, i: number) => argv[i - 1] === "--output") || STORE;

  const genPolicy = argv.includes("--policy") || argv.includes("--all");
  const genRemediation = argv.includes("--remediation") || argv.includes("--all");
  const genPlaybook = argv.includes("--playbook") || argv.includes("--all");

  if (!genPolicy && !genRemediation && !genPlaybook) {
    console.log("  Specify --policy, --remediation, --playbook, or --all. Use --help for details.");
    return;
  }

  if (!existsSync(outputDir)) mkdirSync(outputDir, { recursive: true });

  const generated: string[] = [];

  if (genPolicy) {
    const sections = generatePolicyDoc();
    const content = sections.map((s) => s.content).join("\n");
    const outPath = join(outputDir, "security-policy.md");
    writeFileSync(outPath, content);
    generated.push(outPath);
  }

  if (genRemediation) {
    const sections = generateRemediationGuide();
    const content = sections.map((s) => s.content).join("\n");
    const outPath = join(outputDir, "remediation-guide.md");
    writeFileSync(outPath, content);
    generated.push(outPath);
  }

  if (genPlaybook) {
    const sections = generateTeamPlaybook();
    const content = sections.map((s) => s.content).join("\n");
    const outPath = join(outputDir, "team-playbook.md");
    writeFileSync(outPath, content);
    generated.push(outPath);
  }

  if (format === "json") {
    console.log(JSON.stringify({ generated, outputDir, timestamp: new Date().toISOString() }, null, 2));
  } else {
    console.log(`\n  Documentation Generated\n  ──────────────────────────`);
    for (const g of generated) {
      console.log(`    ✅ ${g}`);
    }
    console.log(`\n  Output directory: ${outputDir}\n`);
  }
}
