/**
 * Hook install — install and configure git hooks for pre-commit
 * and pre-push evaluation with Judges.
 *
 * Supports husky, simple-git-hooks, and direct .git/hooks installation.
 */

// ─── Types ──────────────────────────────────────────────────────────────────

export interface HookConfig {
  /** Hook type: pre-commit or pre-push */
  hook: "pre-commit" | "pre-push";
  /** Only evaluate staged files */
  stagedOnly: boolean;
  /** Fail on findings of this severity or higher */
  failSeverity: string;
  /** Timeout in seconds */
  timeout: number;
  /** Run in parallel */
  parallel: boolean;
  /** Use smart judge selection */
  smartSelect: boolean;
}

// ─── Hook Scripts ───────────────────────────────────────────────────────────

function generateHookScript(config: HookConfig): string {
  const flags: string[] = [];
  if (config.stagedOnly) flags.push("--staged-only");
  if (config.failSeverity !== "info") flags.push(`--min-severity ${config.failSeverity}`);
  flags.push("--fail-on-findings");
  flags.push("--summary");

  return `#!/bin/sh
# Judges ${config.hook} hook
# Auto-generated by: judges hook-install

# Skip if JUDGES_SKIP_HOOK is set
if [ -n "$JUDGES_SKIP_HOOK" ]; then
  echo "Judges: hook skipped (JUDGES_SKIP_HOOK is set)"
  exit 0
fi

# Timeout protection (${config.timeout}s)
timeout_cmd=""
if command -v timeout > /dev/null 2>&1; then
  timeout_cmd="timeout ${config.timeout}"
fi

echo "🔍 Judges: evaluating..."
$timeout_cmd npx judges eval ${flags.join(" ")} 2>&1
exit_code=$?

if [ $exit_code -ne 0 ] && [ $exit_code -ne 124 ]; then
  echo ""
  echo "❌ Judges: findings detected. Fix or skip with JUDGES_SKIP_HOOK=1"
  exit 1
fi

if [ $exit_code -eq 124 ]; then
  echo "⚠️  Judges: evaluation timed out (${config.timeout}s). Proceeding."
fi
`;
}

// ─── Installation Methods ───────────────────────────────────────────────────

function installDirect(hookType: string, script: string): boolean {
  const { writeFileSync, mkdirSync, chmodSync, existsSync } = require("fs");
  const { join } = require("path");

  const hooksDir = join(".git", "hooks");
  if (!existsSync(".git")) {
    console.error("Error: not a git repository");
    return false;
  }

  mkdirSync(hooksDir, { recursive: true });
  const hookPath = join(hooksDir, hookType);
  writeFileSync(hookPath, script, { mode: 0o755 });
  try {
    chmodSync(hookPath, 0o755);
  } catch {
    /* Windows */
  }
  console.log(`  ✅ Installed ${hookPath}`);
  return true;
}

function installHusky(hookType: string, script: string): boolean {
  const { existsSync, writeFileSync, mkdirSync } = require("fs");
  const { join } = require("path");

  if (!existsSync(".husky")) {
    console.log("  Husky directory not found. Creating .husky/");
    mkdirSync(".husky", { recursive: true });
  }

  const hookPath = join(".husky", hookType);
  writeFileSync(hookPath, script, { mode: 0o755 });
  console.log(`  ✅ Installed ${hookPath} (husky)`);
  return true;
}

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runHookInstall(argv: string[]): void {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges hook-install — Install git hooks for automatic code review

Usage:
  judges hook-install                        Install pre-commit hook
  judges hook-install --hook pre-push        Install pre-push hook
  judges hook-install --method husky         Use husky for hook management

Options:
  --hook <type>        Hook type: pre-commit (default) or pre-push
  --method <method>    Installation: direct (default), husky
  --severity <level>   Fail on findings of this severity+ (default: high)
  --timeout <seconds>  Timeout in seconds (default: 60)
  --no-staged-only     Evaluate all files, not just staged
  --uninstall          Remove the hook
  --show               Show current hook script without installing
  --help, -h           Show this help

Environment:
  JUDGES_SKIP_HOOK=1   Skip the hook for a single commit
`);
    return;
  }

  const hookType = (argv.find((_a: string, i: number) => argv[i - 1] === "--hook") || "pre-commit") as
    | "pre-commit"
    | "pre-push";
  const method = argv.find((_a: string, i: number) => argv[i - 1] === "--method") || "direct";
  const severity = argv.find((_a: string, i: number) => argv[i - 1] === "--severity") || "high";
  const timeoutStr = argv.find((_a: string, i: number) => argv[i - 1] === "--timeout");
  const timeout = timeoutStr ? parseInt(timeoutStr, 10) : 60;

  if (argv.includes("--uninstall")) {
    const { unlinkSync, existsSync } = require("fs");
    const { join } = require("path");
    const paths = [join(".git", "hooks", hookType), join(".husky", hookType)];
    for (const p of paths) {
      if (existsSync(p)) {
        unlinkSync(p);
        console.log(`  ✅ Removed ${p}`);
      }
    }
    return;
  }

  const config: HookConfig = {
    hook: hookType,
    stagedOnly: !argv.includes("--no-staged-only"),
    failSeverity: severity,
    timeout,
    parallel: true,
    smartSelect: true,
  };

  const script = generateHookScript(config);

  if (argv.includes("--show")) {
    console.log(script);
    return;
  }

  if (method === "husky") {
    installHusky(hookType, script);
  } else {
    installDirect(hookType, script);
  }
}
