/**
 * PR summary comment — post a top-level comment on a GitHub PR
 * with the overall Judges verdict, score, and finding counts.
 *
 * Uses the GitHub API to create or update a comment with a distinctive
 * marker so subsequent runs update in-place rather than spamming.
 */

import type { TribunalVerdict } from "../types.js";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface PrSummaryOptions {
  owner: string;
  repo: string;
  prNumber: number;
  token: string;
  verdict: TribunalVerdict;
  baseUrl?: string;
}

interface PrSummaryResult {
  commentId: number;
  updated: boolean;
  url: string;
}

// ─── Marker ─────────────────────────────────────────────────────────────────

const COMMENT_MARKER = "<!-- judges-pr-summary -->";

// ─── Formatting ─────────────────────────────────────────────────────────────

function verdictEmoji(verdict: string): string {
  if (verdict === "pass") return "✅";
  if (verdict === "fail") return "❌";
  return "⚠️";
}

function severityBadge(severity: string): string {
  const map: Record<string, string> = { critical: "🔴", high: "🟠", medium: "🟡", low: "🔵", info: "⚪" };
  return map[severity] || "⚪";
}

export function formatPrSummary(verdict: TribunalVerdict): string {
  const emoji = verdictEmoji(verdict.overallVerdict);
  const lines: string[] = [
    COMMENT_MARKER,
    `## ${emoji} Judges Code Review — ${verdict.overallVerdict.toUpperCase()}`,
    "",
    `| Metric | Value |`,
    `|--------|-------|`,
    `| **Verdict** | ${verdict.overallVerdict} |`,
    `| **Score** | ${verdict.overallScore}/100 |`,
    `| **Critical** | ${verdict.criticalCount} |`,
    `| **High** | ${verdict.highCount} |`,
    `| **Judges Run** | ${verdict.evaluations.length} |`,
    "",
  ];

  // Per-judge breakdown
  if (verdict.evaluations.length > 0) {
    lines.push("### Judge Breakdown", "");
    lines.push("| Judge | Verdict | Score | Findings |");
    lines.push("|-------|---------|-------|----------|");

    for (const evaluation of verdict.evaluations) {
      const jEmoji = verdictEmoji(evaluation.verdict);
      const findingCount = evaluation.findings?.length ?? 0;
      lines.push(
        `| ${evaluation.judgeId} | ${jEmoji} ${evaluation.verdict} | ${evaluation.score}/100 | ${findingCount} |`,
      );
    }
    lines.push("");
  }

  // Top findings
  const allFindings = verdict.evaluations.flatMap((e) => e.findings || []);
  const topFindings = allFindings.filter((f) => f.severity === "critical" || f.severity === "high").slice(0, 10);

  if (topFindings.length > 0) {
    lines.push("### Top Findings", "");
    for (const f of topFindings) {
      const badge = severityBadge(f.severity);
      const loc = f.lineNumbers?.length ? ` (line ${f.lineNumbers[0]})` : "";
      lines.push(`- ${badge} **${f.severity.toUpperCase()}** — ${f.ruleId}: ${f.title}${loc}`);
    }
    lines.push("");
  }

  lines.push(
    "---",
    `<sub>Generated by [Judges](https://github.com/KevinRabun/judges) at ${new Date().toISOString()}</sub>`,
  );

  return lines.join("\n");
}

// ─── GitHub API ─────────────────────────────────────────────────────────────

async function findExistingComment(
  owner: string,
  repo: string,
  prNumber: number,
  token: string,
  baseUrl: string,
): Promise<{ id: number; url: string } | null> {
  const url = `${baseUrl}/repos/${owner}/${repo}/issues/${prNumber}/comments?per_page=100`;
  const res = await fetch(url, {
    headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json" },
  });
  if (!res.ok) return null;

  const comments = (await res.json()) as Array<{ id: number; body: string; html_url: string }>;
  const existing = comments.find((c) => c.body.includes(COMMENT_MARKER));
  return existing ? { id: existing.id, url: existing.html_url } : null;
}

export async function postPrSummary(options: PrSummaryOptions): Promise<PrSummaryResult> {
  const baseUrl = options.baseUrl || "https://api.github.com";
  const body = formatPrSummary(options.verdict);
  const headers = {
    Authorization: `Bearer ${options.token}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
  };

  // Check for existing comment to update
  const existing = await findExistingComment(options.owner, options.repo, options.prNumber, options.token, baseUrl);

  if (existing) {
    const url = `${baseUrl}/repos/${options.owner}/${options.repo}/issues/comments/${existing.id}`;
    const res = await fetch(url, {
      method: "PATCH",
      headers,
      body: JSON.stringify({ body }),
    });
    if (!res.ok) throw new Error(`Failed to update comment: ${res.status} ${res.statusText}`);
    return { commentId: existing.id, updated: true, url: existing.url };
  }

  const url = `${baseUrl}/repos/${options.owner}/${options.repo}/issues/${options.prNumber}/comments`;
  const res = await fetch(url, {
    method: "POST",
    headers,
    body: JSON.stringify({ body }),
  });
  if (!res.ok) throw new Error(`Failed to create comment: ${res.status} ${res.statusText}`);

  const data = (await res.json()) as { id: number; html_url: string };
  return { commentId: data.id, updated: false, url: data.html_url };
}

// ─── CLI ────────────────────────────────────────────────────────────────────

export async function runPrSummary(argv: string[]): Promise<void> {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges pr-summary — Post a PR summary comment with Judges results

Usage:
  judges eval --file src/app.ts --format json | judges pr-summary --pr 42 --repo owner/repo

Options:
  --pr <number>          PR number (required)
  --repo <owner/repo>    GitHub repo (auto-detected from git)
  --token <token>        GitHub token (default: GITHUB_TOKEN env)
  --sarif <path>         Read results from SARIF file instead of stdin
  --help, -h             Show this help
`);
    return;
  }

  const { readFileSync, existsSync } = await import("fs");
  const { execSync } = await import("child_process");

  const prArg = argv.find((_a: string, i: number) => argv[i - 1] === "--pr");
  if (!prArg) {
    console.error("Error: --pr <number> is required");
    process.exit(1);
  }
  const prNumber = parseInt(prArg, 10);

  let repoArg = argv.find((_a: string, i: number) => argv[i - 1] === "--repo");
  if (!repoArg) {
    try {
      const remote = execSync("git remote get-url origin", { encoding: "utf-8" }).trim();
      const match = remote.match(/github\.com[:/](.+?)(?:\.git)?$/);
      if (match) repoArg = match[1];
    } catch {
      /* ignore */
    }
  }
  if (!repoArg) {
    console.error("Error: --repo <owner/repo> required (could not auto-detect)");
    process.exit(1);
  }

  const [owner, repo] = repoArg.split("/");
  const token = argv.find((_a: string, i: number) => argv[i - 1] === "--token") || process.env.GITHUB_TOKEN || "";
  if (!token) {
    console.error("Error: --token or GITHUB_TOKEN env required");
    process.exit(1);
  }

  // Load verdict
  const sarifPath = argv.find((_a: string, i: number) => argv[i - 1] === "--sarif");
  let verdict: TribunalVerdict;

  if (sarifPath && existsSync(sarifPath)) {
    // Parse SARIF and synthesize a verdict
    const sarif = JSON.parse(readFileSync(sarifPath, "utf-8"));
    const findings = sarif.runs?.[0]?.results || [];
    verdict = {
      overallVerdict: findings.some((f: { level: string }) => f.level === "error") ? "fail" : "pass",
      overallScore: Math.max(0, 100 - findings.length * 5),
      summary: `SARIF upload with ${findings.length} findings`,
      evaluations: [],
      findings: [],
      criticalCount: findings.filter((f: { level: string }) => f.level === "error").length,
      highCount: findings.filter((f: { level: string }) => f.level === "warning").length,
      timestamp: new Date().toISOString(),
    };
  } else {
    // Try reading JSON verdict from stdin arg or file
    const jsonArg = argv.find((_a: string, i: number) => argv[i - 1] === "--json");
    if (jsonArg && existsSync(jsonArg)) {
      verdict = JSON.parse(readFileSync(jsonArg, "utf-8"));
    } else {
      console.error("Error: provide --sarif <path> or --json <path>");
      process.exit(1);
    }
  }

  const result = await postPrSummary({ owner, repo, prNumber, token, verdict });
  console.log(`${result.updated ? "Updated" : "Created"} PR summary comment: ${result.url}`);
}
