/**
 * Report templates — generate reports from different predefined
 * templates targeting different audiences (exec, dev, compliance).
 *
 * Pure local generation — no external services.
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import type { Finding, TribunalVerdict } from "../types.js";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface ReportTemplate {
  id: string;
  name: string;
  audience: string;
  description: string;
}

// ─── Templates ──────────────────────────────────────────────────────────────

const TEMPLATES: ReportTemplate[] = [
  {
    id: "exec-summary",
    name: "Executive Summary",
    audience: "Leadership",
    description: "One-page overview with verdict, risk score, and trend",
  },
  {
    id: "dev-detail",
    name: "Developer Detail",
    audience: "Developers",
    description: "Full findings with code locations, fixes, and references",
  },
  {
    id: "compliance",
    name: "Compliance Report",
    audience: "Auditors",
    description: "SOC2/ISO-aligned report with policy hash and evidence",
  },
  {
    id: "pr-review",
    name: "PR Review",
    audience: "Code Reviewers",
    description: "Focused diff-aware summary for PR review",
  },
  {
    id: "trend",
    name: "Trend Report",
    audience: "Management",
    description: "Historical comparison showing improvement trajectory",
  },
  {
    id: "onboarding",
    name: "Onboarding Report",
    audience: "New Team Members",
    description: "Gentle introduction to codebase health with learning resources",
  },
];

// ─── Report Generators ─────────────────────────────────────────────────────

function renderExecSummary(verdict: TribunalVerdict): string {
  const critical = verdict.criticalCount || 0;
  const high = verdict.highCount || 0;
  const lines: string[] = [
    "# Executive Summary — Code Review Report",
    "",
    `**Date:** ${new Date().toISOString().split("T")[0]}`,
    `**Verdict:** ${verdict.overallVerdict.toUpperCase()}`,
    `**Score:** ${verdict.overallScore}/100`,
    "",
    "## Risk Overview",
    "",
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Critical findings | ${critical} |`,
    `| High findings | ${high} |`,
    `| Total findings | ${verdict.findings.length} |`,
    `| Judges evaluated | ${verdict.evaluations.length} |`,
    "",
    "## Summary",
    "",
    verdict.summary,
    "",
    "## Action Required",
    "",
  ];

  if (critical > 0) {
    lines.push("**IMMEDIATE ACTION:** Critical findings require attention within 24 hours.");
  } else if (high > 0) {
    lines.push("**ACTION NEEDED:** High-severity findings should be addressed this sprint.");
  } else {
    lines.push("**STATUS:** No critical issues. Continue monitoring.");
  }

  lines.push("", "---", "_Generated by Judges_");
  return lines.join("\n");
}

function renderDevDetail(verdict: TribunalVerdict): string {
  const lines: string[] = [
    "# Developer Report — Detailed Findings",
    "",
    `**Verdict:** ${verdict.overallVerdict} (${verdict.overallScore}/100)`,
    `**Findings:** ${verdict.findings.length}`,
    "",
  ];

  const bySeverity: Record<string, Finding[]> = {};
  for (const f of verdict.findings) {
    (bySeverity[f.severity] ??= []).push(f);
  }

  for (const sev of ["critical", "high", "medium", "low", "info"]) {
    const findings = bySeverity[sev];
    if (!findings?.length) continue;
    lines.push(`## ${sev.toUpperCase()} (${findings.length})`, "");
    for (const f of findings) {
      lines.push(`### ${f.ruleId}: ${f.title}`);
      if (f.lineNumbers?.length) lines.push(`**Lines:** ${f.lineNumbers.join(", ")}`);
      lines.push("", f.description, "");
      lines.push("**Fix:**", f.recommendation, "");
      if (f.reference) lines.push(`**Reference:** ${f.reference}`, "");
      lines.push("---", "");
    }
  }

  return lines.join("\n");
}

function renderComplianceReport(verdict: TribunalVerdict): string {
  const lines: string[] = [
    "# Compliance Report",
    "",
    `**Generated:** ${new Date().toISOString()}`,
    `**Verdict:** ${verdict.overallVerdict}`,
    `**Score:** ${verdict.overallScore}/100`,
    "",
    "## Evaluation Summary",
    "",
    `| Judge | Verdict | Score | Findings |`,
    `|-------|---------|-------|----------|`,
  ];

  for (const e of verdict.evaluations) {
    lines.push(`| ${e.judgeId} | ${e.verdict} | ${e.score} | ${e.findings.length} |`);
  }

  lines.push("", "## Finding Categories", "", "| Severity | Count |", "|----------|-------|");

  const bySev: Record<string, number> = {};
  for (const f of verdict.findings) {
    bySev[f.severity] = (bySev[f.severity] || 0) + 1;
  }
  for (const [s, c] of Object.entries(bySev)) {
    lines.push(`| ${s} | ${c} |`);
  }

  lines.push(
    "",
    "## Evidence",
    "",
    `- Total judges evaluated: ${verdict.evaluations.length}`,
    `- Total findings: ${verdict.findings.length}`,
    `- Critical count: ${verdict.criticalCount || 0}`,
    `- High count: ${verdict.highCount || 0}`,
    "",
    "---",
    "_Audit report generated by Judges_",
  );

  return lines.join("\n");
}

function renderTrendReport(verdict: TribunalVerdict): string {
  const lines: string[] = [
    "# Trend Report",
    "",
    `**Current Score:** ${verdict.overallScore}/100`,
    `**Current Findings:** ${verdict.findings.length}`,
    "",
    "## Current Snapshot",
    "",
  ];

  const bySev: Record<string, number> = {};
  for (const f of verdict.findings) {
    bySev[f.severity] = (bySev[f.severity] || 0) + 1;
  }

  lines.push("| Severity | Count |", "|----------|-------|");
  for (const [s, c] of Object.entries(bySev)) {
    lines.push(`| ${s} | ${c} |`);
  }

  lines.push("", "## Top Rules", "", "| Rule | Count |", "|------|-------|");
  const byRule: Record<string, number> = {};
  for (const f of verdict.findings) {
    byRule[f.ruleId] = (byRule[f.ruleId] || 0) + 1;
  }
  const sorted = Object.entries(byRule)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10);
  for (const [r, c] of sorted) {
    lines.push(`| ${r} | ${c} |`);
  }

  lines.push(
    "",
    "> Compare with `judges regression-alert --check` for baseline comparison.",
    "",
    "---",
    "_Generated by Judges_",
  );
  return lines.join("\n");
}

function renderOnboarding(verdict: TribunalVerdict): string {
  const lines: string[] = [
    "# Welcome to Your Codebase Health Report",
    "",
    "This report helps new team members understand the current code quality state.",
    "",
    `**Overall Score:** ${verdict.overallScore}/100 (${verdict.overallVerdict})`,
    `**Total Findings:** ${verdict.findings.length}`,
    "",
    "## What Do These Findings Mean?",
    "",
    "Findings are categorized by severity:",
    "- **Critical/High:** Security issues that must be fixed",
    "- **Medium:** Best practice violations worth addressing",
    "- **Low/Info:** Suggestions for improvement",
    "",
    "## Key Areas to Learn",
    "",
  ];

  const categories = new Set(verdict.findings.map((f) => f.ruleId.split("-")[0]));
  const catDescriptions: Record<string, string> = {
    SEC: "Security vulnerabilities (injections, XSS, etc.)",
    AUTH: "Authentication and authorization issues",
    CRYPTO: "Cryptography best practices",
    PERF: "Performance optimization opportunities",
    ERR: "Error handling patterns",
    IAC: "Infrastructure as Code security",
    SSRF: "Server-side request forgery prevention",
    CONCUR: "Concurrency and race condition safety",
  };

  for (const cat of categories) {
    lines.push(`- **${cat}:** ${catDescriptions[cat] || "Code quality rules"}`);
  }

  lines.push(
    "",
    "## Getting Started",
    "",
    "1. Run `judges remediation <rule-id>` for fix guides",
    "2. Run `judges explain <rule-id>` for rule details",
    "3. Ask your team lead about suppression policies",
    "",
    "---",
    "_Generated by Judges_",
  );
  return lines.join("\n");
}

// ─── Public API ─────────────────────────────────────────────────────────────

export function listTemplates(): ReportTemplate[] {
  return TEMPLATES;
}

export function generateReport(templateId: string, verdict: TribunalVerdict): string {
  switch (templateId) {
    case "exec-summary":
      return renderExecSummary(verdict);
    case "dev-detail":
      return renderDevDetail(verdict);
    case "compliance":
      return renderComplianceReport(verdict);
    case "trend":
      return renderTrendReport(verdict);
    case "onboarding":
      return renderOnboarding(verdict);
    case "pr-review":
      return renderDevDetail(verdict); // reuse dev detail for PR
    default:
      throw new Error(`Unknown template: ${templateId}. Use --list to see options.`);
  }
}

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runReportTemplate(argv: string[]): void {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges report-template — Generate reports from predefined templates

Usage:
  judges report-template --list                      List available templates
  judges report-template --template exec-summary --input results.json
  judges report-template --template dev-detail --input results.json --output report.md

Options:
  --template <id>       Template to use (required)
  --input <path>        Results JSON file (required)
  --output <path>       Write report to file (default: stdout)
  --list                List available templates
  --help, -h            Show this help

Templates:
  exec-summary    One-page leadership overview
  dev-detail      Full findings with fixes
  compliance      SOC2/ISO-aligned evidence report
  pr-review       Diff-aware PR summary
  trend           Historical comparison
  onboarding      New team member introduction
`);
    return;
  }

  if (argv.includes("--list")) {
    console.log("\n  Report Templates\n  ────────────────");
    for (const t of TEMPLATES) {
      console.log(`    ${t.id.padEnd(16)} ${t.name} (${t.audience})`);
      console.log(`      ${t.description}`);
    }
    console.log("");
    return;
  }

  const templateId = argv.find((_a: string, i: number) => argv[i - 1] === "--template");
  const inputPath = argv.find((_a: string, i: number) => argv[i - 1] === "--input");
  const outputPath = argv.find((_a: string, i: number) => argv[i - 1] === "--output");

  if (!templateId || !inputPath) {
    console.error("Error: --template and --input required");
    process.exit(1);
  }

  if (!existsSync(inputPath)) {
    console.error(`Error: file not found: ${inputPath}`);
    process.exit(1);
  }

  const verdict: TribunalVerdict = JSON.parse(readFileSync(inputPath, "utf-8"));
  const report = generateReport(templateId, verdict);

  if (outputPath) {
    writeFileSync(outputPath, report);
    console.log(`  Report written to ${outputPath}`);
  } else {
    console.log(report);
  }
}
