/**
 * Review-pr-comment-gen — Generate PR comments from review findings.
 */

import { readFileSync, existsSync } from "fs";
import type { TribunalVerdict } from "../types.js";

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runReviewPrCommentGen(argv: string[]): void {
  const reportIdx = argv.indexOf("--report");
  const reportPath = reportIdx >= 0 ? argv[reportIdx + 1] : "";
  const formatIdx = argv.indexOf("--format");
  const format = formatIdx >= 0 ? argv[formatIdx + 1] : "markdown";
  const maxFindings = argv.indexOf("--max");
  const maxCount = maxFindings >= 0 ? parseInt(argv[maxFindings + 1], 10) : 10;

  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges review-pr-comment-gen — Generate PR comments from findings

Usage:
  judges review-pr-comment-gen --report <path> [--max <n>] [--format markdown|json]

Options:
  --report <path>    Path to verdict JSON
  --max <n>          Maximum findings to include (default: 10)
  --format <fmt>     Output format: markdown (default), json
  --help, -h         Show this help
`);
    return;
  }

  if (!reportPath || !existsSync(reportPath)) {
    console.error("Provide --report <path> to a valid verdict JSON file.");
    process.exitCode = 1;
    return;
  }

  const verdict = JSON.parse(readFileSync(reportPath, "utf-8")) as TribunalVerdict;
  const findings = verdict.findings.slice(0, maxCount);

  if (format === "json") {
    console.log(JSON.stringify({ verdict: verdict.overallVerdict, score: verdict.overallScore, findings }, null, 2));
    return;
  }

  const statusEmoji = verdict.overallVerdict === "pass" ? "✅" : verdict.overallVerdict === "fail" ? "❌" : "⚠️";
  const lines: string[] = [];
  lines.push(`## ${statusEmoji} Judges Review — ${verdict.overallVerdict.toUpperCase()}`);
  lines.push("");
  lines.push(
    `**Score:** ${verdict.overallScore}/100 | **Findings:** ${verdict.findings.length} | **Critical:** ${verdict.criticalCount} | **High:** ${verdict.highCount}`,
  );
  lines.push("");

  if (findings.length > 0) {
    lines.push("### Findings");
    lines.push("");
    lines.push("| Severity | Rule | Title | Recommendation |");
    lines.push("|----------|------|-------|----------------|");
    for (const f of findings) {
      const rec = f.recommendation.length > 50 ? f.recommendation.slice(0, 47) + "..." : f.recommendation;
      lines.push(`| ${f.severity} | ${f.ruleId} | ${f.title} | ${rec} |`);
    }
  }

  if (verdict.findings.length > maxCount) {
    lines.push("");
    lines.push(`> Showing ${maxCount} of ${verdict.findings.length} findings. Run \`judges eval\` for full results.`);
  }

  lines.push("");
  lines.push(`<sub>Generated by Judges Panel at ${verdict.timestamp}</sub>`);

  console.log(lines.join("\n"));
}
