/**
 * Review-report-pdf — Generate printable markdown review reports.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { dirname } from "path";
import type { TribunalVerdict } from "../types.js";

// ─── Report Generation ─────────────────────────────────────────────────────

function generateReport(verdict: TribunalVerdict, title: string): string {
  const lines: string[] = [];
  const date = new Date().toISOString().slice(0, 10);

  lines.push(`# ${title}`);
  lines.push(`**Date:** ${date}`);
  lines.push(`**Score:** ${(verdict.overallScore || 0).toFixed(1)}/10`);
  lines.push(`**Verdict:** ${verdict.overallVerdict || "N/A"}`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(verdict.summary || "No summary available.");
  lines.push("");

  // Statistics
  lines.push("## Statistics");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Overall Score | ${(verdict.overallScore || 0).toFixed(1)} |`);
  lines.push(`| Critical Findings | ${verdict.criticalCount || 0} |`);
  lines.push(`| High Findings | ${verdict.highCount || 0} |`);
  lines.push(`| Total Findings | ${(verdict.findings || []).length} |`);
  lines.push(`| Judges Evaluated | ${(verdict.evaluations || []).length} |`);
  lines.push("");

  // Findings by severity
  const findings = verdict.findings || [];
  if (findings.length > 0) {
    lines.push("## Findings");
    lines.push("");

    const criticals = findings.filter((f) => f.severity === "critical");
    const highs = findings.filter((f) => f.severity === "high");
    const mediums = findings.filter((f) => f.severity === "medium");
    const lows = findings.filter((f) => f.severity === "low");

    if (criticals.length > 0) {
      lines.push("### Critical");
      lines.push("");
      for (const f of criticals) {
        lines.push(`- **[${f.ruleId || "N/A"}]** ${f.title || "Untitled"}`);
        if (f.description) lines.push(`  ${f.description}`);
        if (f.recommendation) lines.push(`  *Recommendation:* ${f.recommendation}`);
        lines.push("");
      }
    }

    if (highs.length > 0) {
      lines.push("### High");
      lines.push("");
      for (const f of highs) {
        lines.push(`- **[${f.ruleId || "N/A"}]** ${f.title || "Untitled"}`);
        if (f.description) lines.push(`  ${f.description}`);
        if (f.recommendation) lines.push(`  *Recommendation:* ${f.recommendation}`);
        lines.push("");
      }
    }

    if (mediums.length > 0) {
      lines.push("### Medium");
      lines.push("");
      for (const f of mediums) {
        lines.push(`- **[${f.ruleId || "N/A"}]** ${f.title || "Untitled"}`);
        if (f.recommendation) lines.push(`  *Recommendation:* ${f.recommendation}`);
        lines.push("");
      }
    }

    if (lows.length > 0) {
      lines.push("### Low");
      lines.push("");
      for (const f of lows) {
        lines.push(`- **[${f.ruleId || "N/A"}]** ${f.title || "Untitled"}`);
        lines.push("");
      }
    }
  } else {
    lines.push("## Findings");
    lines.push("");
    lines.push("No findings detected. Code passes all checks.");
    lines.push("");
  }

  // Judge evaluations
  if ((verdict.evaluations || []).length > 0) {
    lines.push("## Judge Evaluations");
    lines.push("");
    lines.push(`| Judge | Verdict | Score | Findings |`);
    lines.push(`|-------|---------|-------|----------|`);
    for (const e of verdict.evaluations || []) {
      lines.push(`| ${e.judgeId} | ${e.verdict} | ${(e.score || 0).toFixed(1)} | ${(e.findings || []).length} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by Judges Panel on ${date}*`);

  return lines.join("\n");
}

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runReviewReportPdf(argv: string[]): void {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges review-report-pdf — Generate printable markdown review reports

Usage:
  judges review-report-pdf --file verdict.json     Generate report
  judges review-report-pdf --file v.json --output report.md  Save to file
  judges review-report-pdf --file v.json --title "Sprint Review"

Options:
  --file <path>         Verdict JSON file
  --output <path>       Output file path (default: stdout)
  --title <text>        Report title (default: "Code Review Report")
  --format json         JSON output (report metadata)
  --help, -h            Show this help

Generates detailed markdown reports suitable for printing or sharing.
`);
    return;
  }

  const format = argv.find((_a: string, i: number) => argv[i - 1] === "--format") || "text";
  const file = argv.find((_a: string, i: number) => argv[i - 1] === "--file");
  const output = argv.find((_a: string, i: number) => argv[i - 1] === "--output");
  const title = argv.find((_a: string, i: number) => argv[i - 1] === "--title") || "Code Review Report";

  if (!file || !existsSync(file)) {
    console.error("Error: --file with valid verdict JSON is required.");
    process.exitCode = 1;
    return;
  }

  let verdict: TribunalVerdict;
  try {
    verdict = JSON.parse(readFileSync(file, "utf-8")) as TribunalVerdict;
  } catch {
    console.error("Error: Failed to parse verdict file.");
    process.exitCode = 1;
    return;
  }

  if (format === "json") {
    console.log(
      JSON.stringify(
        {
          title,
          date: new Date().toISOString().slice(0, 10),
          score: verdict.overallScore || 0,
          verdict: verdict.overallVerdict || "N/A",
          findings: (verdict.findings || []).length,
          criticals: verdict.criticalCount || 0,
        },
        null,
        2,
      ),
    );
    return;
  }

  const report = generateReport(verdict, title);

  if (output) {
    mkdirSync(dirname(output), { recursive: true });
    writeFileSync(output, report, "utf-8");
    console.log(`Report saved to ${output}`);
    return;
  }

  console.log(report);
}
