/**
 * Review-pr-comment — Generate PR comment summaries from review results.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import type { TribunalVerdict } from "../types.js";

// ─── Types ──────────────────────────────────────────────────────────────────

interface PRComment {
  title: string;
  body: string;
  verdict: string;
  score: number;
  findingCount: number;
  criticalCount: number;
  highCount: number;
}

// ─── Generator ──────────────────────────────────────────────────────────────

function generatePRComment(verdict: TribunalVerdict, title: string): PRComment {
  const findings = verdict.findings || [];
  const criticalCount = verdict.criticalCount || findings.filter((f) => f.severity === "critical").length;
  const highCount = verdict.highCount || findings.filter((f) => f.severity === "high").length;
  const mediumCount = findings.filter((f) => f.severity === "medium").length;
  const lowCount = findings.filter((f) => f.severity === "low").length;

  const scoreEmoji = verdict.overallScore >= 8 ? "🟢" : verdict.overallScore >= 5 ? "🟡" : "🔴";
  const verdictText = verdict.overallVerdict || (verdict.overallScore >= 7 ? "pass" : "fail");

  let body = `## ${scoreEmoji} Judges Panel Review\n\n`;
  body += `**Verdict:** ${verdictText.toUpperCase()} | **Score:** ${verdict.overallScore}/10\n\n`;

  if (findings.length === 0) {
    body += "✨ No findings — code looks good!\n";
  } else {
    body += `### Findings Summary\n\n`;
    body += `| Severity | Count |\n|----------|-------|\n`;
    if (criticalCount > 0) body += `| 🔴 Critical | ${criticalCount} |\n`;
    if (highCount > 0) body += `| 🟠 High | ${highCount} |\n`;
    if (mediumCount > 0) body += `| 🟡 Medium | ${mediumCount} |\n`;
    if (lowCount > 0) body += `| 🟢 Low | ${lowCount} |\n`;
    body += `\n**Total:** ${findings.length} finding(s)\n\n`;

    // Top findings
    const top = findings.slice(0, 5);
    if (top.length > 0) {
      body += `### Top Findings\n\n`;
      for (const f of top) {
        const sev = (f.severity || "medium").toUpperCase();
        body += `- **[${sev}]** ${f.ruleId}: ${f.title}\n`;
        if (f.recommendation) body += `  - Fix: ${f.recommendation}\n`;
      }
    }
  }

  body += `\n---\n*Generated by [Judges Panel](https://github.com/KevinRabun/judges)*\n`;

  return {
    title,
    body,
    verdict: verdictText,
    score: verdict.overallScore,
    findingCount: findings.length,
    criticalCount,
    highCount,
  };
}

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runReviewPrComment(argv: string[]): void {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges review-pr-comment — Generate PR comment summaries

Usage:
  judges review-pr-comment --file report.json
  judges review-pr-comment --file report.json --out pr-comment.md
  judges review-pr-comment --file report.json --format json

Options:
  --file <path>         Path to a tribunal verdict JSON file
  --out <path>          Output path for the comment (default: stdout)
  --title <text>        Comment title
  --format json         JSON output
  --help, -h            Show this help

Generates a formatted markdown comment suitable for GitHub/GitLab PRs.
Output saved to .judges/pr-comment.md.
`);
    return;
  }

  const filePath = argv.find((_a: string, i: number) => argv[i - 1] === "--file");
  const outPath = argv.find((_a: string, i: number) => argv[i - 1] === "--out");
  const title = argv.find((_a: string, i: number) => argv[i - 1] === "--title") || "Code Review";
  const format = argv.find((_a: string, i: number) => argv[i - 1] === "--format") || "text";

  if (!filePath || !existsSync(filePath)) {
    console.error("Error: --file is required and must exist.");
    process.exitCode = 1;
    return;
  }

  let verdict: TribunalVerdict;
  try {
    verdict = JSON.parse(readFileSync(filePath, "utf-8")) as TribunalVerdict;
  } catch {
    console.error("Error: Could not parse verdict file.");
    process.exitCode = 1;
    return;
  }

  const comment = generatePRComment(verdict, title);

  if (format === "json") {
    console.log(JSON.stringify(comment, null, 2));
    return;
  }

  const defaultOut = outPath || join(".judges", "pr-comment.md");
  mkdirSync(dirname(defaultOut), { recursive: true });
  writeFileSync(defaultOut, comment.body, "utf-8");

  console.log(comment.body);
  console.log(`\nComment saved to ${defaultOut}`);
}
