/**
 * Review-summary — Generate PR-ready review summaries with key metrics.
 */

import { readFileSync } from "fs";
import type { TribunalVerdict } from "../types.js";

// ─── Types ──────────────────────────────────────────────────────────────────

interface SummaryMetrics {
  totalFindings: number;
  criticalCount: number;
  highCount: number;
  mediumCount: number;
  lowCount: number;
  judgeCount: number;
  overallScore: number;
  overallVerdict: string;
  topRules: { ruleId: string; count: number }[];
}

// ─── Metrics extraction ─────────────────────────────────────────────────────

function extractMetrics(verdict: TribunalVerdict): SummaryMetrics {
  const findings = verdict.findings || [];
  const severityCounts: Record<string, number> = { critical: 0, high: 0, medium: 0, low: 0 };

  const ruleCounts = new Map<string, number>();
  for (const f of findings) {
    const sev = f.severity || "low";
    severityCounts[sev] = (severityCounts[sev] || 0) + 1;
    const rid = f.ruleId || "unknown";
    ruleCounts.set(rid, (ruleCounts.get(rid) || 0) + 1);
  }

  const topRules = [...ruleCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([ruleId, count]) => ({ ruleId, count }));

  return {
    totalFindings: findings.length,
    criticalCount: severityCounts["critical"],
    highCount: severityCounts["high"],
    mediumCount: severityCounts["medium"],
    lowCount: severityCounts["low"],
    judgeCount: verdict.evaluations?.length || 0,
    overallScore: verdict.overallScore ?? 0,
    overallVerdict: verdict.overallVerdict || "unknown",
    topRules,
  };
}

// ─── Formatters ─────────────────────────────────────────────────────────────

function severityEmoji(count: number, level: string): string {
  if (count === 0) return `✅ 0 ${level}`;
  if (level === "critical") return `🔴 ${count} ${level}`;
  if (level === "high") return `🟠 ${count} ${level}`;
  if (level === "medium") return `🟡 ${count} ${level}`;
  return `🔵 ${count} ${level}`;
}

function verdictEmoji(verdict: string): string {
  const map: Record<string, string> = {
    pass: "✅ PASS",
    fail: "❌ FAIL",
    warning: "⚠️ WARNING",
  };
  return map[verdict] || verdict.toUpperCase();
}

function formatMarkdown(metrics: SummaryMetrics): string {
  const lines: string[] = [];

  lines.push(`## Judges Review Summary`);
  lines.push(``);
  lines.push(
    `**Verdict:** ${verdictEmoji(metrics.overallVerdict)} | **Score:** ${metrics.overallScore}/100 | **Judges:** ${metrics.judgeCount}`,
  );
  lines.push(``);
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| ${severityEmoji(metrics.criticalCount, "critical")} | ${metrics.criticalCount} |`);
  lines.push(`| ${severityEmoji(metrics.highCount, "high")} | ${metrics.highCount} |`);
  lines.push(`| ${severityEmoji(metrics.mediumCount, "medium")} | ${metrics.mediumCount} |`);
  lines.push(`| ${severityEmoji(metrics.lowCount, "low")} | ${metrics.lowCount} |`);
  lines.push(`| **Total** | **${metrics.totalFindings}** |`);

  if (metrics.topRules.length > 0) {
    lines.push(``);
    lines.push(`**Top Rules:**`);
    for (const r of metrics.topRules) {
      lines.push(`- \`${r.ruleId}\` (${r.count})`);
    }
  }

  lines.push(``);
  lines.push(`---`);
  lines.push(`*Generated by [Judges Panel](https://github.com/KevinRabun/judges)*`);

  return lines.join("\n");
}

function formatSlack(metrics: SummaryMetrics): string {
  const lines: string[] = [];

  lines.push(`*Judges Review Summary*`);
  lines.push(
    `Verdict: ${verdictEmoji(metrics.overallVerdict)} | Score: ${metrics.overallScore}/100 | Judges: ${metrics.judgeCount}`,
  );
  lines.push(``);
  lines.push(
    `${severityEmoji(metrics.criticalCount, "critical")} | ${severityEmoji(metrics.highCount, "high")} | ${severityEmoji(metrics.mediumCount, "medium")} | ${severityEmoji(metrics.lowCount, "low")}`,
  );
  lines.push(`Total: ${metrics.totalFindings} findings`);

  if (metrics.topRules.length > 0) {
    lines.push(``);
    lines.push(`Top rules: ${metrics.topRules.map((r) => `${r.ruleId} (${r.count})`).join(", ")}`);
  }

  return lines.join("\n");
}

function formatOneLiner(metrics: SummaryMetrics): string {
  return `${verdictEmoji(metrics.overallVerdict)} Score: ${metrics.overallScore}/100 | ${metrics.totalFindings} findings (${metrics.criticalCount}C/${metrics.highCount}H/${metrics.mediumCount}M/${metrics.lowCount}L) | ${metrics.judgeCount} judges`;
}

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runReviewSummary(argv: string[]): void {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges review-summary — Generate PR-ready review summary

Usage:
  judges review-summary --input verdict.json
  judges review-summary --input verdict.json --style markdown
  judges review-summary --input verdict.json --style slack
  judges review-summary --format json

Options:
  --input <file>       JSON file with TribunalVerdict (required)
  --style <type>       Output style: text, markdown, slack, oneliner (default: text)
  --format json        Raw JSON metrics output
  --help, -h           Show this help

Styles:
  text                 Plain text summary (default)
  markdown             GitHub PR description format
  slack                Slack message format
  oneliner             Single-line summary

Generates a concise, copy-pasteable review summary suitable for
PR descriptions, Slack messages, or CI logs.
`);
    return;
  }

  const inputPath = argv.find((_a: string, i: number) => argv[i - 1] === "--input");
  const style = argv.find((_a: string, i: number) => argv[i - 1] === "--style") || "text";
  const format = argv.find((_a: string, i: number) => argv[i - 1] === "--format") || "text";

  if (!inputPath) {
    console.error("Error: --input is required. Provide a JSON verdict file.");
    process.exitCode = 1;
    return;
  }

  let verdict: TribunalVerdict;
  try {
    const raw = readFileSync(inputPath, "utf-8");
    verdict = JSON.parse(raw) as TribunalVerdict;
  } catch {
    console.error(`Error: Cannot read or parse ${inputPath}`);
    process.exitCode = 1;
    return;
  }

  const metrics = extractMetrics(verdict);

  if (format === "json") {
    console.log(JSON.stringify(metrics, null, 2));
    return;
  }

  switch (style) {
    case "markdown":
      console.log(formatMarkdown(metrics));
      break;
    case "slack":
      console.log(formatSlack(metrics));
      break;
    case "oneliner":
      console.log(formatOneLiner(metrics));
      break;
    default:
      console.log(`\n  Review Summary\n  ─────────────────────────────`);
      console.log(`    Verdict: ${verdictEmoji(metrics.overallVerdict)}`);
      console.log(`    Score: ${metrics.overallScore}/100`);
      console.log(`    Judges: ${metrics.judgeCount}`);
      console.log(`    Total findings: ${metrics.totalFindings}`);
      console.log(`      ${severityEmoji(metrics.criticalCount, "critical")}`);
      console.log(`      ${severityEmoji(metrics.highCount, "high")}`);
      console.log(`      ${severityEmoji(metrics.mediumCount, "medium")}`);
      console.log(`      ${severityEmoji(metrics.lowCount, "low")}`);
      if (metrics.topRules.length > 0) {
        console.log(`\n    Top Rules:`);
        for (const r of metrics.topRules) {
          console.log(`      ${r.ruleId} (${r.count})`);
        }
      }
      console.log();
      break;
  }
}
