/**
 * Review-summary-email — Generate email-ready review summaries.
 */

import { readFileSync, existsSync } from "fs";

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runReviewSummaryEmail(argv: string[]): void {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges review-summary-email — Generate email-ready review summaries

Usage:
  judges review-summary-email --file results.json
  judges review-summary-email --file results.json --to team@example.com
  judges review-summary-email --file results.json --format json

Options:
  --file <path>         Path to review result JSON
  --to <email>          Recipient (included in subject line, not sent)
  --subject <text>      Custom subject line
  --format json         JSON output
  --help, -h            Show this help

Generates a formatted text suitable for copy-paste into email.
Does NOT send email — output is local only.
`);
    return;
  }

  const format = argv.find((_a: string, i: number) => argv[i - 1] === "--format") || "text";
  const filePath = argv.find((_a: string, i: number) => argv[i - 1] === "--file") || "";
  const to = argv.find((_a: string, i: number) => argv[i - 1] === "--to") || "";
  const customSubject = argv.find((_a: string, i: number) => argv[i - 1] === "--subject") || "";

  if (!filePath) {
    console.log("Specify --file <path> to a review result JSON.");
    return;
  }

  if (!existsSync(filePath)) {
    console.log(`File not found: ${filePath}`);
    return;
  }

  let data: Record<string, unknown>;
  try {
    data = JSON.parse(readFileSync(filePath, "utf-8")) as Record<string, unknown>;
  } catch {
    console.log(`Failed to parse: ${filePath}`);
    return;
  }

  const score = typeof data.overallScore === "number" ? data.overallScore : 0;
  const verdict = typeof data.overallVerdict === "string" ? data.overallVerdict : "unknown";
  const summary = typeof data.summary === "string" ? data.summary : "";
  const criticalCount = typeof data.criticalCount === "number" ? data.criticalCount : 0;
  const highCount = typeof data.highCount === "number" ? data.highCount : 0;
  const findings = Array.isArray(data.findings) ? data.findings : [];
  const timestamp = typeof data.timestamp === "string" ? data.timestamp : new Date().toISOString();

  const subject = customSubject || `Code Review Report — Score ${score.toFixed(1)}/10 (${verdict})`;

  if (format === "json") {
    console.log(
      JSON.stringify(
        {
          to,
          subject,
          body: { score, verdict, summary, criticalCount, highCount, findingCount: findings.length, timestamp },
        },
        null,
        2,
      ),
    );
    return;
  }

  // Generate email text
  const lines: string[] = [];
  lines.push("─".repeat(60));
  if (to) lines.push(`To: ${to}`);
  lines.push(`Subject: ${subject}`);
  lines.push(`Date: ${timestamp.slice(0, 10)}`);
  lines.push("─".repeat(60));
  lines.push("");
  lines.push("CODE REVIEW SUMMARY");
  lines.push("═".repeat(40));
  lines.push(`Score:     ${score.toFixed(1)} / 10`);
  lines.push(`Verdict:   ${verdict.toUpperCase()}`);
  lines.push(`Findings:  ${findings.length} total (${criticalCount} critical, ${highCount} high)`);
  lines.push("");

  if (summary) {
    lines.push("Overview:");
    lines.push(`  ${summary}`);
    lines.push("");
  }

  if (findings.length > 0) {
    lines.push("Top Findings:");
    const top = findings.slice(0, 5);
    for (const f of top) {
      const sev = typeof f === "object" && f && "severity" in f ? String((f as Record<string, unknown>).severity) : "?";
      const title =
        typeof f === "object" && f && "title" in f ? String((f as Record<string, unknown>).title) : "untitled";
      const rule = typeof f === "object" && f && "ruleId" in f ? String((f as Record<string, unknown>).ruleId) : "";
      lines.push(`  [${sev.toUpperCase()}] ${rule} — ${title}`);
    }
    if (findings.length > 5) {
      lines.push(`  ... and ${findings.length - 5} more findings`);
    }
    lines.push("");
  }

  lines.push("─".repeat(60));
  lines.push("Generated by Judges Panel — https://github.com/KevinRabun/judges");
  lines.push("─".repeat(60));

  console.log(lines.join("\n"));
}
