/**
 * Review-export-pdf — Export review results to PDF-ready markdown.
 *
 * Generates a structured markdown document suitable for PDF conversion
 * via external tools (pandoc, md-to-pdf, etc.).
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { dirname } from "path";
import type { TribunalVerdict } from "../types.js";

// ─── Helpers ────────────────────────────────────────────────────────────────

function verdictToMarkdown(verdict: TribunalVerdict, title: string): string {
  const lines: string[] = [];

  lines.push(`# ${title}`);
  lines.push("");
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push(`**Verdict:** ${verdict.overallVerdict} (Score: ${verdict.overallScore})`);
  lines.push(`**Findings:** ${verdict.findings.length} total`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(verdict.summary);
  lines.push("");

  // Severity breakdown
  lines.push("## Severity Breakdown");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  lines.push(`| Critical | ${verdict.criticalCount} |`);
  lines.push(`| High | ${verdict.highCount} |`);

  const medCount = verdict.findings.filter((f) => (f.severity || "medium").toLowerCase() === "medium").length;
  const lowCount = verdict.findings.filter((f) => (f.severity || "medium").toLowerCase() === "low").length;
  lines.push(`| Medium | ${medCount} |`);
  lines.push(`| Low | ${lowCount} |`);
  lines.push("");

  // Findings
  lines.push("## Findings");
  lines.push("");

  for (let i = 0; i < verdict.findings.length; i++) {
    const f = verdict.findings[i];
    lines.push(`### ${i + 1}. ${f.title}`);
    lines.push("");
    lines.push(`- **Rule:** ${f.ruleId}`);
    lines.push(`- **Severity:** ${f.severity || "medium"}`);
    if (f.confidence !== undefined && f.confidence !== null) {
      lines.push(`- **Confidence:** ${(f.confidence * 100).toFixed(0)}%`);
    }
    if (f.lineNumbers && f.lineNumbers.length > 0) {
      lines.push(`- **Lines:** ${f.lineNumbers.join(", ")}`);
    }
    lines.push("");
    lines.push(f.description);
    lines.push("");
    if (f.recommendation) {
      lines.push(`**Recommendation:** ${f.recommendation}`);
      lines.push("");
    }
  }

  // Judge evaluations
  if (verdict.evaluations && verdict.evaluations.length > 0) {
    lines.push("## Judge Evaluations");
    lines.push("");
    lines.push("| Judge | Verdict | Score | Findings |");
    lines.push("|-------|---------|-------|----------|");
    for (const e of verdict.evaluations) {
      lines.push(`| ${e.judgeId} | ${e.verdict} | ${e.score} | ${e.findings.length} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Report generated by Judges Panel*");

  return lines.join("\n");
}

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runReviewExportPdf(argv: string[]): void {
  const fileIdx = argv.indexOf("--file");
  const outputIdx = argv.indexOf("--output");
  const titleIdx = argv.indexOf("--title");
  const filePath = fileIdx >= 0 ? argv[fileIdx + 1] : undefined;
  const outputPath = outputIdx >= 0 ? argv[outputIdx + 1] : undefined;
  const title = titleIdx >= 0 ? argv[titleIdx + 1] : "Code Review Report";

  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges review-export-pdf — Export review results as PDF-ready markdown

Usage:
  judges review-export-pdf --file <verdict.json> [--output <report.md>]
                            [--title <title>]

Options:
  --file <path>      Path to verdict JSON file (required)
  --output <path>    Output markdown file (default: stdout)
  --title <text>     Report title (default: "Code Review Report")
  --help, -h         Show this help

Convert to PDF:
  pandoc report.md -o report.pdf
  npx md-to-pdf report.md
`);
    return;
  }

  if (!filePath) {
    console.error("Error: --file required");
    process.exitCode = 1;
    return;
  }
  if (!existsSync(filePath)) {
    console.error(`Error: file not found: ${filePath}`);
    process.exitCode = 1;
    return;
  }

  let verdict: TribunalVerdict;
  try {
    verdict = JSON.parse(readFileSync(filePath, "utf-8"));
  } catch {
    console.error("Error: invalid JSON");
    process.exitCode = 1;
    return;
  }

  const markdown = verdictToMarkdown(verdict, title);

  if (outputPath) {
    const d = dirname(outputPath);
    if (!existsSync(d)) mkdirSync(d, { recursive: true });
    writeFileSync(outputPath, markdown);
    console.log(`Report written to: ${outputPath}`);
  } else {
    console.log(markdown);
  }
}
