/**
 * Review-merge-request — Format findings for merge/pull request comments.
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import type { Finding, TribunalVerdict } from "../types.js";

// ─── Formatting ─────────────────────────────────────────────────────────────

function toMarkdownComment(verdict: TribunalVerdict): string {
  const lines: string[] = [];
  lines.push(`## Judges Review Summary`);
  lines.push(``);
  lines.push(
    `**Verdict:** ${verdict.overallVerdict} | **Score:** ${verdict.overallScore} | **Findings:** ${verdict.findings.length}`,
  );
  lines.push(``);

  if (verdict.criticalCount > 0 || verdict.highCount > 0) {
    lines.push(`> ⚠️ ${verdict.criticalCount} critical, ${verdict.highCount} high severity finding(s)`);
    lines.push(``);
  }

  const bySeverity: Record<string, Finding[]> = {};
  for (const f of verdict.findings) {
    if (bySeverity[f.severity] === undefined) {
      bySeverity[f.severity] = [];
    }
    bySeverity[f.severity].push(f);
  }

  const order = ["critical", "high", "medium", "low", "info"];
  for (const sev of order) {
    const group = bySeverity[sev];
    if (group === undefined || group.length === 0) continue;

    lines.push(`### ${sev.charAt(0).toUpperCase() + sev.slice(1)} (${group.length})`);
    lines.push(``);
    for (const f of group) {
      const loc = f.lineNumbers !== undefined && f.lineNumbers.length > 0 ? ` (L${f.lineNumbers.join(",")})` : "";
      lines.push(`- **${f.ruleId}**${loc}: ${f.title}`);
      lines.push(`  - ${f.recommendation}`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(
    `*Generated by [Judges](https://github.com/KevinRabun/judges) at ${verdict.timestamp ?? new Date().toISOString()}*`,
  );

  return lines.join("\n");
}

// ─── CLI ────────────────────────────────────────────────────────────────────

export function runReviewMergeRequest(argv: string[]): void {
  const fileIdx = argv.indexOf("--file");
  const outputIdx = argv.indexOf("--output");
  const formatIdx = argv.indexOf("--format");
  const filePath = fileIdx >= 0 ? argv[fileIdx + 1] : undefined;
  const outputPath = outputIdx >= 0 ? argv[outputIdx + 1] : undefined;
  const format = formatIdx >= 0 ? argv[formatIdx + 1] : "markdown";

  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`
judges review-merge-request — Format findings for MR/PR comments

Usage:
  judges review-merge-request --file <review.json> [--output <file>]
                              [--format markdown|json]

Options:
  --file <path>     Review result JSON file
  --output <path>   Write formatted comment to file
  --format <fmt>    Output format: markdown (default), json
  --help, -h        Show this help
`);
    return;
  }

  if (!filePath) {
    console.error("Error: --file is required");
    process.exitCode = 1;
    return;
  }

  if (!existsSync(filePath)) {
    console.error(`Error: file not found: ${filePath}`);
    process.exitCode = 1;
    return;
  }

  let verdict: TribunalVerdict;
  try {
    verdict = JSON.parse(readFileSync(filePath, "utf-8")) as TribunalVerdict;
  } catch {
    console.error(`Error: failed to parse review file: ${filePath}`);
    process.exitCode = 1;
    return;
  }

  if (format === "json") {
    console.log(JSON.stringify({ comment: toMarkdownComment(verdict) }, null, 2));
    return;
  }

  const output = toMarkdownComment(verdict);

  if (outputPath) {
    writeFileSync(outputPath, output);
    console.log(`MR comment written to ${outputPath}`);
    return;
  }

  console.log(output);
}
