// ─── Conversational Review Tool Handlers ─────────────────────────────────────
// MCP tools for interactive finding review: explaining findings, triaging,
// querying lifecycle stats, and viewing suppression analytics.
// ──────────────────────────────────────────────────────────────────────────────

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

import {
  loadFindingStore,
  triageFinding,
  getTriagedFindings,
  formatTriageSummary,
  getFindingStats,
  getSuppressionAnalytics,
  formatSuppressionAnalytics,
} from "../finding-lifecycle.js";
import type { TriageStatus } from "../finding-lifecycle.js";
import { evaluateWithTribunal } from "../evaluators/index.js";
import type { EvaluationOptions } from "../evaluators/index.js";

// ─── Rule-prefix learning context (shared with CLI --explain) ────────────────

const RULE_PREFIX_CONTEXT: Record<string, { owasp?: string; cwe?: string; learn: string }> = {
  SEC: {
    owasp: "A03:2021 Injection",
    cwe: "CWE-79/CWE-89",
    learn: "Input validation prevents injection attacks where untrusted data is sent to an interpreter.",
  },
  AUTH: {
    owasp: "A07:2021 Identification and Authentication Failures",
    cwe: "CWE-287",
    learn: "Authentication flaws let attackers compromise passwords, keys, or session tokens.",
  },
  CRYPTO: {
    owasp: "A02:2021 Cryptographic Failures",
    cwe: "CWE-327/CWE-328",
    learn: "Weak or missing cryptography exposes sensitive data to interception and tampering.",
  },
  DATA: {
    owasp: "A02:2021 Cryptographic Failures",
    cwe: "CWE-200/CWE-312",
    learn: "Sensitive data exposure occurs when applications do not adequately protect data at rest or in transit.",
  },
  CYBER: {
    owasp: "A01:2021 Broken Access Control",
    cwe: "CWE-284",
    learn: "Access control enforces policy so users cannot act outside their intended permissions.",
  },
  INJ: {
    owasp: "A03:2021 Injection",
    cwe: "CWE-89/CWE-78",
    learn: "Injection flaws occur when hostile data is sent to an interpreter as part of a command or query.",
  },
  XSS: {
    owasp: "A03:2021 Injection",
    cwe: "CWE-79",
    learn: "Cross-site scripting (XSS) lets attackers inject scripts into web pages viewed by other users.",
  },
  SSRF: {
    owasp: "A10:2021 Server-Side Request Forgery",
    cwe: "CWE-918",
    learn:
      "SSRF lets attackers make the server send requests to unintended locations, potentially accessing internal services.",
  },
  PERF: { learn: "Performance issues cause slow response times, high resource usage, or scalability bottlenecks." },
  A11Y: {
    learn: "Accessibility ensures applications are usable by people with disabilities, per WCAG 2.1 guidelines.",
  },
  AICS: {
    owasp: "OWASP AI Security",
    learn: "AI code safety rules detect prompt injection, model poisoning, and unsafe AI integration patterns.",
  },
  IAC: {
    learn:
      "Infrastructure as Code security ensures cloud resources are provisioned with least-privilege, encryption, and audit logging.",
  },
  COMP: { learn: "Compliance rules enforce regulatory requirements like GDPR, HIPAA, PCI-DSS, and SOC 2." },
  DSEC: {
    learn: "Dependency security rules flag known-vulnerable packages, outdated dependencies, and supply-chain risks.",
  },
  API: {
    learn:
      "API contract rules enforce input validation, proper status codes, content-type, rate limiting, and versioning on REST endpoints.",
  },
  HALLU: {
    learn:
      "Hallucination detection catches fabricated APIs, non-existent imports, and phantom methods commonly generated by AI models.",
  },
};

/**
 * Register conversational review tools: explain_finding, triage_finding,
 * get_finding_stats, get_suppression_analytics.
 */
export function registerReviewTools(server: McpServer): void {
  registerExplainFinding(server);
  registerTriageFinding(server);
  registerGetFindingStats(server);
  registerGetSuppressionAnalytics(server);
  registerListTriagedFindings(server);
  registerReEvaluateWithContext(server);
}

// ─── explain_finding ─────────────────────────────────────────────────────────

function registerExplainFinding(server: McpServer): void {
  server.tool(
    "explain_finding",
    "Explain a Judges Panel finding in plain language. Provides OWASP/CWE references, risk context, and remediation guidance based on the rule ID and finding details.",
    {
      ruleId: z.string().describe("The finding rule ID (e.g., SEC-001, AUTH-002, XSS-001)"),
      title: z.string().optional().describe("The finding title for additional context"),
      description: z.string().optional().describe("The finding description to explain"),
      severity: z.string().optional().describe("The finding severity (critical, high, medium, low, info)"),
      codeSnippet: z.string().optional().describe("The code snippet that triggered the finding"),
    },
    async ({ ruleId, title, description, severity, codeSnippet }) => {
      const prefix = ruleId.replace(/-\d+$/, "");
      const ctx = RULE_PREFIX_CONTEXT[prefix];

      const sections: string[] = [];
      sections.push(`# Finding Explanation: ${ruleId}`);
      if (title) sections.push(`\n**${title}**`);
      if (severity) sections.push(`\n**Severity:** ${severity.toUpperCase()}`);

      if (description) {
        sections.push(`\n## What was found\n${description}`);
      }

      if (codeSnippet) {
        sections.push(`\n## Affected code\n\`\`\`\n${codeSnippet}\n\`\`\``);
      }

      if (ctx) {
        sections.push(`\n## Why this matters\n${ctx.learn}`);
        if (ctx.owasp) sections.push(`\n**OWASP Top 10:** ${ctx.owasp}`);
        if (ctx.cwe) sections.push(`**CWE:** ${ctx.cwe}`);
      }

      // Provide remediation pointers based on prefix
      const remediation = getRemediationGuidance(prefix);
      if (remediation) {
        sections.push(`\n## Remediation\n${remediation}`);
      }

      sections.push(
        `\n## Next steps\n- Use \`triage_finding\` to accept, defer, or dismiss this finding\n- Use \`fix_code\` to auto-fix if a patch is available\n- Use \`evaluate_code\` to re-evaluate after fixing`,
      );

      const structured = {
        ruleId,
        prefix,
        title: title ?? null,
        severity: severity ?? null,
        owasp: ctx?.owasp ?? null,
        cwe: ctx?.cwe ?? null,
        learn: ctx?.learn ?? null,
        remediation: getRemediationGuidance(prefix) ?? null,
      };

      return {
        content: [
          { type: "text" as const, text: sections.join("\n") },
          { type: "text" as const, text: "```json\n" + JSON.stringify(structured, null, 2) + "\n```" },
        ],
      };
    },
  );
}

function getRemediationGuidance(prefix: string): string | undefined {
  const guidance: Record<string, string> = {
    SEC: "Validate and sanitize all user inputs. Use parameterized queries for databases, context-aware output encoding for HTML, and allowlists over denylists.",
    AUTH: "Use established authentication libraries. Enforce strong passwords, implement MFA, use secure session management, and never store credentials in code.",
    CRYPTO:
      "Use well-known cryptographic libraries (e.g., libsodium, Web Crypto API). Avoid MD5/SHA1 for security, use AES-256-GCM or ChaCha20-Poly1305 for encryption.",
    XSS: "Escape all dynamic content before rendering in HTML. Use Content Security Policy headers. Prefer framework auto-escaping (React JSX, Angular templates).",
    INJ: "Use parameterized queries or prepared statements. Never concatenate user input into SQL, shell commands, or LDAP queries.",
    SSRF: "Validate and allowlist URLs before making server-side requests. Block private IP ranges (10.x, 172.16-31.x, 192.168.x, 127.x). Use DNS pinning.",
    DATA: "Encrypt sensitive data at rest and in transit. Remove secrets from logs. Use environment variables or secret managers for credentials.",
    PERF: "Profile before optimizing. Focus on hot paths, reduce allocations, cache expensive computations, and avoid N+1 query patterns.",
    IAC: "Follow least-privilege principle. Enable encryption at rest, audit logging, and network segmentation. Use managed identities over API keys.",
    DSEC: "Update vulnerable dependencies promptly. Use lock files, enable automated security updates, and audit transitive dependencies.",
    AICS: "Validate AI model inputs and outputs. Implement prompt injection defenses, rate limiting, and content filtering for AI-integrated applications.",
  };
  return guidance[prefix];
}

// ─── triage_finding ──────────────────────────────────────────────────────────

function registerTriageFinding(server: McpServer): void {
  server.tool(
    "triage_finding",
    "Set the triage status of a tracked finding. Records the decision (accepted-risk, deferred, wont-fix, false-positive) with attribution and reason. Feeds back into calibration to reduce future false positives.",
    {
      ruleId: z.string().describe("Rule ID to triage (e.g., SEC-001)"),
      filePath: z
        .string()
        .optional()
        .describe("Optional file path to narrow the match when multiple findings share the same rule"),
      status: z
        .enum(["accepted-risk", "deferred", "wont-fix", "false-positive"])
        .describe(
          "Triage decision: accepted-risk (keep but acknowledged), deferred (fix later), wont-fix (will not address), false-positive (incorrect finding)",
        ),
      reason: z.string().optional().describe("Explanation for the triage decision"),
      triagedBy: z.string().optional().describe("Who made this decision (person or team)"),
      dir: z
        .string()
        .optional()
        .describe("Project directory containing .judges-findings.json (default: current directory)"),
    },
    async ({ ruleId, filePath, status, reason, triagedBy, dir }) => {
      try {
        const projectDir = dir || ".";
        const result = triageFinding(
          projectDir,
          { ruleId, filePath: filePath || undefined },
          status as TriageStatus,
          reason,
          triagedBy,
        );

        if (!result) {
          return {
            content: [
              {
                type: "text" as const,
                text: `No matching open findings found for rule \`${ruleId}\`${filePath ? ` in ${filePath}` : ""}. Run an evaluation first to populate the finding store.`,
              },
            ],
          };
        }

        return {
          content: [
            {
              type: "text" as const,
              text: `✓ Triaged finding \`${result.ruleId}\` in ${result.filePath} as **${status}**${reason ? `\n\nReason: ${reason}` : ""}${triagedBy ? `\nTriaged by: ${triagedBy}` : ""}`,
            },
            {
              type: "text" as const,
              text:
                "```json\n" +
                JSON.stringify(
                  {
                    ruleId: result.ruleId,
                    filePath: result.filePath,
                    status,
                    reason: reason ?? null,
                    triagedBy: triagedBy ?? null,
                  },
                  null,
                  2,
                ) +
                "\n```",
            },
          ],
        };
      } catch (error) {
        return {
          content: [
            {
              type: "text" as const,
              text: error instanceof Error ? `Error: ${error.message}` : "Error: Failed to triage finding",
            },
          ],
          isError: true,
        };
      }
    },
  );
}

// ─── get_finding_stats ───────────────────────────────────────────────────────

function registerGetFindingStats(server: McpServer): void {
  server.tool(
    "get_finding_stats",
    "Get finding lifecycle statistics for the project: open, fixed, recurring, and triaged finding counts plus trends. Shows whether code quality is improving or declining over evaluation runs.",
    {
      dir: z
        .string()
        .optional()
        .describe("Project directory containing .judges-findings.json (default: current directory)"),
      format: z.enum(["text", "json"]).optional().describe("Output format (default: text)"),
    },
    async ({ dir, format }) => {
      try {
        const projectDir = dir || ".";
        const stats = getFindingStats(projectDir);

        if (format === "json") {
          return {
            content: [{ type: "text" as const, text: JSON.stringify(stats, null, 2) }],
          };
        }

        const lines: string[] = [];
        lines.push("# Finding Lifecycle Statistics\n");
        lines.push(`| Metric | Count |`);
        lines.push(`|--------|-------|`);
        lines.push(`| Open | ${stats.totalOpen} |`);
        lines.push(`| Fixed | ${stats.totalFixed} |`);
        lines.push(`| Triaged | ${stats.totalTriaged} |`);
        lines.push(`| Evaluation runs | ${stats.runCount} |`);
        lines.push(`| Avg open age (days) | ${stats.avgAge.toFixed(1)} |`);

        if (stats.oldestOpen) {
          lines.push(`| Oldest open finding | ${stats.oldestOpen.slice(0, 10)} |`);
        }

        const total = stats.totalOpen + stats.totalFixed + stats.totalTriaged;
        if (total > 0) {
          const fixRate = ((stats.totalFixed / total) * 100).toFixed(1);
          const openRate = ((stats.totalOpen / total) * 100).toFixed(1);
          lines.push(`\n**Fix rate:** ${fixRate}% · **Open rate:** ${openRate}%`);
        }

        // Triage status breakdown
        const triageEntries = Object.entries(stats.byTriageStatus);
        if (triageEntries.length > 0) {
          lines.push(`\n## Triage breakdown\n`);
          lines.push(`| Status | Count |`);
          lines.push(`|--------|-------|`);
          for (const [s, c] of triageEntries) {
            lines.push(`| ${s} | ${c} |`);
          }
        }

        // Top rules by count
        const ruleEntries = Object.entries(stats.byRule)
          .sort((a, b) => b[1] - a[1])
          .slice(0, 10);
        if (ruleEntries.length > 0) {
          lines.push(`\n## Most common open rules\n`);
          lines.push(`| Rule | Count |`);
          lines.push(`|------|-------|`);
          for (const [r, c] of ruleEntries) {
            lines.push(`| ${r} | ${c} |`);
          }
        }

        return {
          content: [{ type: "text" as const, text: lines.join("\n") }],
        };
      } catch (error) {
        return {
          content: [
            {
              type: "text" as const,
              text: error instanceof Error ? `Error: ${error.message}` : "Error: Failed to get finding stats",
            },
          ],
          isError: true,
        };
      }
    },
  );
}

// ─── get_suppression_analytics ───────────────────────────────────────────────

function registerGetSuppressionAnalytics(server: McpServer): void {
  server.tool(
    "get_suppression_analytics",
    "Analyze finding suppression patterns: FP rates by rule, suppression rates by judge, auto-suppress candidates, and actionable recommendations for tuning. Use this to understand which rules need calibration.",
    {
      dir: z
        .string()
        .optional()
        .describe("Project directory containing .judges-findings.json (default: current directory)"),
      fpThreshold: z
        .number()
        .min(0)
        .max(1)
        .optional()
        .describe("FP rate threshold for auto-suppress candidates (default: 0.7)"),
      minSamples: z
        .number()
        .int()
        .positive()
        .optional()
        .describe("Minimum sample count for a rule to be considered (default: 3)"),
      format: z.enum(["text", "json"]).optional().describe("Output format (default: text)"),
    },
    async ({ dir, fpThreshold, minSamples, format }) => {
      try {
        const projectDir = dir || ".";
        const analytics = getSuppressionAnalytics(projectDir, { fpThreshold, minSamples });

        if (format === "json") {
          return {
            content: [{ type: "text" as const, text: JSON.stringify(analytics, null, 2) }],
          };
        }

        const text = formatSuppressionAnalytics(analytics);
        return {
          content: [{ type: "text" as const, text }],
        };
      } catch (error) {
        return {
          content: [
            {
              type: "text" as const,
              text:
                error instanceof Error ? `Error: ${error.message}` : "Error: Failed to compute suppression analytics",
            },
          ],
          isError: true,
        };
      }
    },
  );
}

// ─── list_triaged_findings ───────────────────────────────────────────────────

function registerListTriagedFindings(server: McpServer): void {
  server.tool(
    "list_triaged_findings",
    "List findings that have been triaged (accepted-risk, deferred, wont-fix, false-positive). Optionally filter by triage status. Shows the triage decision, reason, and who made it.",
    {
      dir: z
        .string()
        .optional()
        .describe("Project directory containing .judges-findings.json (default: current directory)"),
      status: z
        .enum(["accepted-risk", "deferred", "wont-fix", "false-positive"])
        .optional()
        .describe("Filter to a specific triage status"),
      format: z.enum(["text", "json"]).optional().describe("Output format (default: text)"),
    },
    async ({ dir, status, format }) => {
      try {
        const projectDir = dir || ".";
        const store = loadFindingStore(projectDir);

        if (format === "json") {
          const findings = getTriagedFindings(store, status as TriageStatus | undefined);
          return {
            content: [{ type: "text" as const, text: JSON.stringify(findings, null, 2) }],
          };
        }

        if (status) {
          const findings = getTriagedFindings(store, status as TriageStatus);
          if (findings.length === 0) {
            return {
              content: [{ type: "text" as const, text: `No findings with status **${status}** found.` }],
            };
          }

          const lines: string[] = [];
          lines.push(`# Triaged Findings — ${status}\n`);
          lines.push(`| Rule | File | Reason | By | Date |`);
          lines.push(`|------|------|--------|----|------|`);
          for (const f of findings) {
            lines.push(
              `| ${f.ruleId} | ${f.filePath} | ${f.triageReason || "—"} | ${f.triagedBy || "—"} | ${f.triagedAt?.slice(0, 10) || "—"} |`,
            );
          }
          return {
            content: [{ type: "text" as const, text: lines.join("\n") }],
          };
        }

        // Full summary
        const summary = formatTriageSummary(store);
        return {
          content: [{ type: "text" as const, text: summary }],
        };
      } catch (error) {
        return {
          content: [
            {
              type: "text" as const,
              text: error instanceof Error ? `Error: ${error.message}` : "Error: Failed to list triaged findings",
            },
          ],
          isError: true,
        };
      }
    },
  );
}

// ─── re_evaluate_with_context ────────────────────────────────────────────────

function registerReEvaluateWithContext(server: McpServer): void {
  server.tool(
    "re_evaluate_with_context",
    "Re-evaluate code with developer-provided context from a multi-turn conversation. Accepts disputed findings, accepted findings, and additional context to adjust the evaluation. This is the agentic feedback loop — the developer explains their intent and the tribunal re-evaluates with that context, applying auto-tune and confidence filtering.",
    {
      code: z.string().describe("The source code to re-evaluate"),
      language: z.string().describe("Programming language (e.g., typescript, python, go)"),
      disputedRuleIds: z
        .array(z.string())
        .optional()
        .describe("Rule IDs the developer disputes as false positives (e.g., ['SEC-001', 'PERF-003'])"),
      acceptedRuleIds: z
        .array(z.string())
        .optional()
        .describe("Rule IDs the developer accepts (these will not be filtered)"),
      developerContext: z
        .string()
        .optional()
        .describe(
          "Free-form explanation from the developer about their intent, design decisions, or why certain findings are incorrect",
        ),
      focusAreas: z
        .array(z.string())
        .optional()
        .describe("Specific areas to focus the re-evaluation on (e.g., ['security', 'performance'])"),
      confidenceFilter: z
        .number()
        .min(0)
        .max(1)
        .optional()
        .describe("Minimum confidence threshold — findings below this are dropped (default: 0.5)"),
      filePath: z.string().optional().describe("File path for context-aware evaluation"),
      deepReview: z
        .boolean()
        .optional()
        .describe("Whether to include the LLM deep-review prompt section in the result"),
      relatedFiles: z
        .array(
          z.object({
            path: z.string().describe("Path of the related file"),
            snippet: z.string().describe("Relevant code snippet from the related file"),
            relationship: z.string().optional().describe("Relationship to the main file (e.g., 'imports', 'tests')"),
          }),
        )
        .optional()
        .describe("Cross-file context for more accurate evaluation"),
    },
    async ({
      code,
      language,
      disputedRuleIds,
      acceptedRuleIds,
      developerContext,
      focusAreas,
      confidenceFilter,
      filePath,
      deepReview,
      relatedFiles,
    }) => {
      try {
        // Build context string from developer inputs
        const contextParts: string[] = [];
        if (developerContext) {
          contextParts.push(`Developer context: ${developerContext}`);
        }
        if (disputedRuleIds && disputedRuleIds.length > 0) {
          contextParts.push(`Disputed findings: ${disputedRuleIds.join(", ")}`);
        }
        if (acceptedRuleIds && acceptedRuleIds.length > 0) {
          contextParts.push(`Accepted findings: ${acceptedRuleIds.join(", ")}`);
        }
        if (focusAreas && focusAreas.length > 0) {
          contextParts.push(`Focus areas: ${focusAreas.join(", ")}`);
        }
        const fullContext = contextParts.join("\n");

        const evalOptions: EvaluationOptions = {
          autoTune: true,
          deepReview: deepReview ?? false,
          confidenceFilter: confidenceFilter ?? 0.5,
          filePath,
          relatedFiles,
          calibrate: true,
        };

        const verdict = evaluateWithTribunal(code, language, fullContext || undefined, evalOptions);

        // Post-process: mark disputed findings
        let findings = verdict.findings;
        if (disputedRuleIds && disputedRuleIds.length > 0) {
          const disputedSet = new Set(disputedRuleIds);
          findings = findings.map((f) => {
            if (disputedSet.has(f.ruleId)) {
              return {
                ...f,
                confidence: Math.max(0.1, (f.confidence ?? 0.5) * 0.5),
                confidenceTier: "supplementary" as const,
              };
            }
            return f;
          });
          // Re-filter after confidence adjustment
          if (confidenceFilter) {
            findings = findings.filter((f) => (f.confidence ?? 0.5) >= confidenceFilter);
          }
        }

        const sections: string[] = [];
        sections.push(`# Re-Evaluation Results\n`);
        sections.push(`**Verdict:** ${verdict.overallVerdict} · **Score:** ${verdict.overallScore}/100`);
        sections.push(`**Findings:** ${findings.length} (after context adjustment)`);

        if (verdict.autoTuneApplied) {
          sections.push(
            `**Auto-tune:** ${verdict.autoTuneApplied.suppressed} suppressed, ${verdict.autoTuneApplied.downgraded} downgraded`,
          );
        }
        if (verdict.confidenceFilterApplied) {
          sections.push(
            `**Confidence filter:** ${verdict.confidenceFilterApplied.filteredOut} findings below ${Math.round(verdict.confidenceFilterApplied.threshold * 100)}% filtered out`,
          );
        }

        if (findings.length > 0) {
          sections.push(`\n## Findings\n`);
          for (const f of findings) {
            const conf =
              f.confidence !== undefined && f.confidence !== null ? ` (${Math.round(f.confidence * 100)}%)` : "";
            const tier = f.confidenceTier ? ` [${f.confidenceTier}]` : "";
            sections.push(`- **${f.ruleId}** ${f.severity}${conf}${tier}: ${f.title}`);
          }
        }

        if (disputedRuleIds && disputedRuleIds.length > 0) {
          const stillPresent = findings.filter((f) => disputedRuleIds.includes(f.ruleId));
          const resolved = disputedRuleIds.filter((id) => !findings.some((f) => f.ruleId === id));
          if (resolved.length > 0) {
            sections.push(`\n## Disputed findings resolved\n`);
            sections.push(`The following disputed findings were dropped: ${resolved.join(", ")}`);
          }
          if (stillPresent.length > 0) {
            sections.push(`\n## Disputed findings retained\n`);
            sections.push(
              `The following remain with reduced confidence: ${stillPresent.map((f) => `${f.ruleId} (${Math.round((f.confidence ?? 0) * 100)}%)`).join(", ")}`,
            );
          }
        }

        const structured = {
          overallVerdict: verdict.overallVerdict,
          overallScore: verdict.overallScore,
          findingCount: findings.length,
          autoTuneApplied: verdict.autoTuneApplied ?? null,
          confidenceFilterApplied: verdict.confidenceFilterApplied ?? null,
          disputedResolved: disputedRuleIds?.filter((id) => !findings.some((f) => f.ruleId === id)) ?? [],
          findings: findings.map((f) => ({
            ruleId: f.ruleId,
            severity: f.severity,
            confidence: f.confidence,
            confidenceTier: f.confidenceTier,
            title: f.title,
          })),
        };

        const contentBlocks = [
          { type: "text" as const, text: sections.join("\n") },
          { type: "text" as const, text: "```json\n" + JSON.stringify(structured, null, 2) + "\n```" },
        ];

        if (verdict.deepReviewPrompt) {
          contentBlocks.push({ type: "text" as const, text: verdict.deepReviewPrompt });
        }

        return { content: contentBlocks };
      } catch (error) {
        return {
          content: [
            {
              type: "text" as const,
              text: error instanceof Error ? `Error: ${error.message}` : "Error: Re-evaluation failed",
            },
          ],
          isError: true,
        };
      }
    },
  );
}
